### ISSUE TITLE
Getting started - object 'rhandsontable_html' not found error

### ISSUE THREAD

**Issue by julienbarrere2** [DillonHammill/CytoExploreR#100]
Hi, 

I have been trying to get started on the demo and I am getting stuck... I have tried everything I could think of, including re-installing everything but I still get the same error. When I run the following line:

gs <- cyto_setup("Compensation-Samples", gatingTemplate = "Compensation-gatingTemplate.csv")

I get the following error: 

object 'rhandsontable_html' not found. 

I have attached the image of the error. Any chance I could get some help?

Thank you so so much.

Best, 

Julien

<img width="841" alt="error" src="https://user-images.githubusercontent.com/17927830/101431266-84f80100-38d4-11eb-9fbf-06edeebc45e3.png">

**Comment by DillonHammill** [comment]
Hmmm, this is wierd. Never seen this one before. Can you paste the output of `sessionInfo()` here so I can take a look?

**Comment by julienbarrere2** [comment]
Hi Dillon,

Thank you so so much for replying! Here is the sessionInfo():

R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:
/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK:
/Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] shiny_1.5.0            CytoExploreRData_1.0.3 CytoExploreR_1.0.8
openCyto_2.3.0         flowWorkspace_4.2.0
[6] flowCore_2.3.0

loaded via a namespace (and not attached):
  [1] Rtsne_0.15          colorspace_2.0-0    ellipsis_0.3.1
 mclust_5.4.7        cytolib_2.2.0
  [6] corpcor_1.6.9       base64enc_0.1-3     clue_0.3-58
rstudioapi_0.13     hexbin_1.28.1
 [11] IDPmisc_1.1.20      RSpectra_0.16-0     mvtnorm_1.1-1
xml2_1.3.2          splines_4.0.3
 [16] R.methodsS3_1.8.1   mnormt_2.0.2        robustbase_0.93-6
knitr_1.30          shinythemes_1.1.2
 [21] jsonlite_1.7.1      umap_0.2.7.0        cluster_2.1.0       png_0.1-7
          R.oo_1.24.0
 [26] graph_1.68.0        rrcov_1.5-5         compiler_4.0.3
 httr_1.4.2          rainbow_3.6
 [31] Matrix_1.2-18       fastmap_1.0.1       later_1.1.0.1
visNetwork_2.0.9    htmltools_0.5.0
 [36] tools_4.0.3         ncdfFlow_2.36.0     rsvd_1.0.3
 gtable_0.3.0        glue_1.4.2
 [41] reshape2_1.4.4      dplyr_1.0.2         Rcpp_1.0.5
 Biobase_2.50.0      vctrs_0.3.5
 [46] changepoint_2.2.2   xfun_0.19           stringr_1.4.0       mime_0.9
           lifecycle_0.2.0
 [51] gtools_3.8.2        XML_3.99-0.5        DEoptimR_1.0-8
 zlibbioc_1.36.0     MASS_7.3-53
 [56] zoo_1.8-8           scales_1.1.1        EmbedSOM_2.1.1
 RProtoBufLib_2.3.0  promises_1.1.1
 [61] parallel_4.0.3      RBGL_1.66.0         RColorBrewer_1.1-2
 yaml_2.2.1          curl_4.3
 [66] reticulate_1.18     aws.signature_0.6.0 ggplot2_3.3.2
latticeExtra_0.6-29 stringi_1.5.3
 [71] S4Vectors_0.28.0    pcaPP_1.9-73        flowClust_3.28.0
 flowAI_1.20.1       BiocGenerics_0.36.0
 [76] hdrcde_3.3          flowViz_1.54.0      rlang_0.4.9
pkgconfig_2.0.3     matrixStats_0.57.0
 [81] bitops_1.0-6        evaluate_0.14       fda_5.1.7
lattice_0.20-41     purrr_0.3.4
 [86] ks_1.11.7           htmlwidgets_1.5.2   tidyselect_1.1.0
 plyr_1.8.6          magrittr_2.0.1
 [91] R6_2.5.0            generics_0.1.0      pillar_1.4.7
 RCurl_1.98-1.2      tibble_3.0.4
 [96] crayon_1.3.4        KernSmooth_2.23-18  ellipse_0.4.2
tmvnsim_1.0-2       rhandsontable_0.3.7
[101] rmarkdown_2.5       fds_1.8             aws.s3_0.3.21
jpeg_0.1-8.1        grid_4.0.3
[106] data.table_1.13.2   Rgraphviz_2.34.0    digest_0.6.27
xtable_1.8-4        tidyr_1.1.2
[111] httpuv_1.5.4        R.utils_2.10.1      flowStats_4.3.0
openssl_1.4.3       RcppParallel_5.0.2
[116] stats4_4.0.3        munsell_0.5.0       askpass_1.1

Best,

Julien

**Comment by DillonHammill** [comment]
Hmmm, looks like your `rhandsontable` version is correct and I can confirm that the version you have works on my machine. I think we will need to try removing and reinstalling `rhandsontable` to see if that fixes the problem. Can you please restart your R session and run the following:
```{r}
remove.packages("rhandsontable")
install.packages("rhandsontable")
```

Then load in CytoExploreR and try to run the code again:
```{r}
library(CytoExploreR)
```

If that doesn't work, can you try and load `rhandsontable` as well before running the code again:
```{r}
library(rhandsontable)
```

Please paste the output of the code as you run it here so I help you figure out what is going wrong.

**Comment by julienbarrere2** [comment]
Here is is:

> remove.packages("rhandsontable")
Removing package from
‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library’
(as ‘lib’ is unspecified)
> install.packages("rhandsontable")
trying URL '
https://cran.rstudio.com/bin/macosx/contrib/4.0/rhandsontable_0.3.7.tgz'
Content type 'application/x-gzip' length 3626360 bytes (3.5 MB)
==================================================
downloaded 3.5 MB


The downloaded binary packages are in
/var/folders/1r/qbbmdjx931g5dqcp2mhn4fg00000gn/T//RtmprnJywN/downloaded_packages

> library(CytoExploreR)
Loading required package: flowCore
Loading required package: flowWorkspace
As part of improvements to flowWorkspace, some behavior of
GatingSet objects has changed. For details, please read the section
titled "The cytoframe and cytoset classes" in the package vignette:

  vignette("flowWorkspace-Introduction", "flowWorkspace")
Loading required package: openCyto
> library(rhandsontable)

> gs <- cyto_setup("Compensation-Samples", gatingTemplate =
"Compensation-gatingTemplate.csv")
Loading FCS files into a GatingSet...
Assigning markers to channels...
Loading required package: shiny


And this is where it keeps running, I need to stop the process, as it was
happening before, getting the same error message as before...

Thank you so so much!

Best,

Julien

**Comment by DillonHammill** [comment]
Can you try running:
```{r}
CytoExploreR:::data_editor(mtcars)
```
Let me know if the table is displayed in the viewer pane or not. This will most likely generate the same error.

**Comment by julienbarrere2** [comment]
It generates the table in the viewer but I get the same error yeah, I need
to force the end of the process. cyto_setup was also generating the table.

**Comment by julienbarrere2** [comment]
Hi Dillon,

I have re-installed absolutely everything (R, Rstudio, all packages, etc.)
and still run into the same error. I get the same problem when I try to
load my data. Did you have the chance to give it more thought?

Thank you so much,

Julien

**Comment by DillonHammill** [comment]
@julienbarrere2, I had a look the `rhandsontable` code and there is no `rhandsontable_html` object anywhere in the package and I certainly have not used it either. I am a bit confused where this is coming from and it is difficult for me to track it down without being able to replicate the problem.

I am going to check to see if this is happening in the latest `docker` image - if so I can try and debug it there...

**Comment by DillonHammill** [comment]
Have you tried installing the development version of rhandsontable?
```{r}
devtools::install_github("jrowen/rhandsontable")
```

**Comment by DillonHammill** [comment]
If that does not work can you try running the following and let me know if the table is displayed and whether you get the same error?
```{r}
rhandsontable(mtcars)
```

**Comment by julienbarrere2** [comment]
I tried it, and I can display mtcars well when I run rhandsontable(mtcars)

When I run

gs <- cyto_setup("Compensation-Samples",gatingTemplate =
"Compensation-gatingTemplate.csv")

The consol will display the following:

Loading FCS files into a GatingSet...
Assigning markers to channels...

The table is displayed (which was the case before too), but I still need to
abort the process and get the same error: object 'rhandsontable_html' not
found

Thank you for your help so far!

**Comment by julienbarrere2** [comment]
Hi,

I tried reinstalling everything again, and now run in a new problem...

When running

devtools::install_github("DillonHammill/CytoExploreR")

I get the following error message:

ERROR: lazy loading failed for package ‘CytoExploreR’
* removing
‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/CytoExploreR’
Error: Failed to install 'CytoExploreR' from GitHub:
  (converted from warning) installation of package
‘/var/folders/1r/qbbmdjx931g5dqcp2mhn4fg00000gn/T//Rtmp1hbPxH/file2797d964f4f/CytoExploreR_1.0.8.tar.gz’
had non-zero exit status

Thank you!

**Comment by DillonHammill** [comment]
This is likely because `remotes` is converting warnings to errors, you can turn this off as follows:
```{r}
Sys.setenv("R_REMOTES_NO_ERRORS_FROM_WARNINGS" = "true")
devtools::install_github("DillonHammill/CytoExploreR")
```

**Comment by DillonHammill** [comment]
I have also checked the docker image, and everything works as expected. I think this problem may be caused by `shiny` - I am looking into this as we speak...

**Comment by DillonHammill** [comment]
Hmmm... looks like we have the same version of `shiny` as well. Perhaps we could connect over zoom so that you can share your screen with me? If you send an email to `CytoExploreR@outlook.com` with a suitable time I can send through a meeting link.

**Comment by helenaboutzen** [comment]
Hi I am getting the exact same error today.  I am not sure if this error has been resolved ?
thanks
Helena

**Comment by DillonHammill** [comment]
Hi @helenaboutzen, from memory I think a fresh install of CytoExploreR fixed the issue and don't forget to use the `Save and Close` button. If you are still having issues please contact me via email to `CytoExploreR@outlook.com` abd we can connect over zoom to resolve the problem.

**Comment by helenaboutzen** [comment]
Hi thanks. this is resolved. I did not see the Save and Close button hidden with my small screen. thanks for the quick reply

**Comment by DillonHammill** [comment]
No problem. The editor interfaces are getting a major update in the next version of CytoExploreR thanks to the DataEditR package. The buttons will be in more visible locations at the top of the editors.
