### ISSUE TITLE
Boolean gate

### ISSUE THREAD

**Issue by mimisikai** [DillonHammill/CytoExploreR#104]
I have a complicated Boolean gate flow: A+B+C-D-E-F-,
by trying to have the expression like: A&B!C!D!E!F, but do not work. 
Could you please advise how to set up the Boolean expression here? Thanks.

**Comment by DillonHammill** [comment]
I suspect that you may need `&` signs in front of all the `!` as well.

**Comment by DillonHammill** [comment]
Closing this issue as I believe the issue has been resolved. Feel free to reopen if you need help
