### ISSUE TITLE
cyto_setup stuck forever 

### ISSUE THREAD

**Issue by mimisikai** [DillonHammill/CytoExploreR#105]
Install per instructions. When loading samples, the cyto_setup function cannot walk through, it's stuck at "assigning markers to channels". 
gs = cyto_setup(path = "xxxx", gatingTemplate = "gatingTemplate.csv")
Loading FCS files into a GatingSet...
Assigning markers to channels...

**Comment by DillonHammill** [comment]
If you scroll through the table in the viewer pane there is a save & close button that must be hit to proceed to the next step.

**Comment by mimisikai** [comment]
sorry for this silly question.

**Comment by DillonHammill** [comment]
No worries. Happy to help!
