### ISSUE TITLE
Negative value on axis is incorrect

### ISSUE THREAD

**Issue by tamaikeiichi** [DillonHammill/CytoExploreR#108]
**Describe the bug**
On biexp axis in a flow cytometry graph,
True signal value: negative value (e.g., -100, acquired from SONY SA3800)
Displayed value on axis: positive value (e.g., 10^-2) 
Same results both in 1-D and 2-D plot.

**To Reproduce**
Analyzed plot by CytoExploreR and screenshot on SA3800 software are below.
![cytoexplorer](https://user-images.githubusercontent.com/28277966/111433507-b5580280-8741-11eb-9053-97f6ef5ea5ef.jpeg)
![SA3800](https://user-images.githubusercontent.com/28277966/111433510-b6892f80-8741-11eb-925f-56d76a334aee.jpg)

**Expected behavior**
Could you change to display the true signal value (negative number)?

**Desktop (please complete the following information):**
 - OS: mac

**Additional context**
Thank you for your great packages!

**Comment by DillonHammill** [comment]
Well spotted! Thanks for reporting this. Looks like I put the negative sign in the wrong place. I will work on a fix tomorrow morning.

**Comment by DillonHammill** [comment]
@tamaikeiichi, this should now be fixed! Please pull down the latest version of CytoExploreR from the `master` branch:
```{r}
devtools::install_github("DillonHammill/CytoExploreR")
```

**Comment by tamaikeiichi** [comment]
Thank you for your immediate response, Great work!
