### ISSUE TITLE
CytoExploreR-Manual-Gating: Interval gate axes are flipped

### ISSUE THREAD

**Issue by gringer** [DillonHammill/CytoExploreR#113]
I'm running through the 'Manual Gating' vignette, and noticed that the axes for interval gating are the wrong way round.

**To Reproduce**
According to the vignette, this should be the commands run:

```
# Interval gate
cyto_gate_draw(cs,
               alias = "T Cells",
               channels = c("CD44", "Va2"),
               type = "interval",
               axes_trans = trans)

```
This has CD44 on the X axis and Va2 on the Y axis

**Expected behavior**
According to the animated image on the vignette, Va2 should be on the X axis, and CD44 on the Y axis.

**Desktop (please complete the following information):**
    $ uname -a
    Linux elegans 5.6.0-1-amd64 #1 SMP Debian 5.6.7-1 (2020-04-29) x86_64 GNU/Linux

**Additional context**

Downloaded from github today [51ef3528]

**Comment by DillonHammill** [comment]
@gringer, thanks for spotting the typo on the website. I have just updated the website and CytoExploreR version to 1.1.0.
