### ISSUE TITLE
Error with installation instructions

### ISSUE THREAD

**Issue by mblue9** [DillonHammill/CytoExploreR#119]
**Describe the bug**
I just started trying out this package (really enjoying it!) and thought I should let you know about an error I got with one of the installation instructions in case others experience it.

**To Reproduce**
I was following the instructions on the home page here https://dillonhammill.github.io/CytoExploreR/index.html and this

```
devtools::install_github("RGLab/cytoinstaller")
cytoinstaller::install_cyto(bioc_ver = "devel")
```
produced this error for me
```
Error in cyto_pkg_github_url(pkg, owner, ...) : 
  Error : GitHub PAT must have one of these forms:
  * 40 hexadecimal digits (older PATs)
  * A 'ghp_' prefix followed by 36 to 251 more characters (newer PATs)
```

I ended up just doing `devtools::install_github("RGLab/cytoverse")` and was able to run the code in Getting started but wondering if the instruction should be below as that seems to work to install the cytoverse Bioc devel versions, if they're the versions that are supposed to be installed?
```
devtools::install_github("RGLab/cytoverse")
cytoverse::cytoverse_update(repo = "bioconductor", branch="devel")
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac

**Additional context**

**Comment by rwbaer** [comment]
FWIW, CytoExploreR has seemed to be running fine  for me with the regular Bioconductor versions of of RGLab packages.   Should we really still be working off the development branch?

**Comment by DillonHammill** [comment]
GitHub versions of RGLab packages are no longer required. Either installation method is fine for RGLab packages but `bioc_ver = "devel")` is no longer necessary.
