### ISSUE TITLE
Update CytoExploreR Installation Instructions

### ISSUE THREAD

**Issue by DillonHammill** [DillonHammill/CytoExploreR#12]
In order to make installation of RGLab dependencies easier for Windows users, users can instead opt to install R devel (R4.0) and install all the pre-compiled RGLab binaries from BioConductor-devel. Note that this method relies on package binaries being available (which may not always be the case) and package updates to the github versions will only be reflected in the BioConductor versions a day later.

**Install CytoExploreR on Windows R 4.0**
1. Install the development version of [R](https://cran.r-project.org/bin/windows/base/rdevel.html).
2. Install the latest version of [RStudio](https://rstudio.com/products/rstudio/download/).
3. From within RStudio run the following to get the `devel` version of `BiocManager`:
```{r}
if (!requireNamespace("BiocManager", quietly=TRUE))
    install.packages("BiocManager")
BiocManager::install(version = "devel")
```
4. Install the `devel` versions of the RGLab packages on BioConductor in a step-wise manner. If any pop-ups ask if you would like to install from source select NO.
```{r}
library(BiocManager)
install("flowCore", type = "binary")
install("flowWorkspace", type = "binary")
install("openCyto", type = "binary")
```
5. Install `CytoExploreRData` and `CytoExploreR` from GitHub:
```{r}
tryCatch(library(devtools), error = function(e){
  install.packages("devtools")
  library(devtools)
})
devtools::install_github("DillonHammill/CytoExploreRData")
devtools::install_github("DillonHammill/CytoExploreR")
```

The process outlined above bypasses the need for setting up the package compilers, but only works for R 4.0 and if RGLab binaries are available. If you want to install `CytoExploreR` on an older version of R, you will need to setup the compilers correctly as outlined in the README. 

The installation instructions for `flowClust` require updating, so you may experience issues compiling this package. Once these installation instructions are updated I will post them here for those who may need them.

**Comment by northNomad** [comment]
Hey @DillonHammill ,

Thank you again for the development - it's such a powerful package.

I think it'd be beneficial to have a section on how to update the package from console.
For example, when ```cyto_gate_draw()``` was released, (due to my own inexperience), I didn't know how to quickly update the package and there was no instruction readily available. 
So I uninstalled R and re-installed everything; it was time-consuming and I know that was not the best way to do it.

Regards,
NN

**Comment by DillonHammill** [comment]
The BioConductor binary for flowClust is now available, so you should not have issues installing this package unless you accidentally indicate that you want to install the source package.

**Comment by DillonHammill** [comment]
**Install CytoExploreR on mac OS X**

1. Install the latest public release version of [r](https://cran.r-project.org/bin/macosx/). The latest version is currently R-3.6.3.
2. Install Xcode developer tools from the [App Store](https://apps.apple.com/us/app/xcode/id497799835?mt=12). 
3. Open the terminal and run `xcode-select --install` to install command line tools.
4. Install mac OS toolchain  y installing clang 8.0.0 and gfortran 6.1 [here](https://cran.r-project.org/bin/macosx/tools/).
5. Check if `XQuartz` is listed in your installed Applications (it may be in the Utilities folder). If `XQuartz` is missing on your machine, you can install it from the [XQuartz](https://www.xquartz.org/) website.
6. Install `RStudio` from the [RStudio](https://rstudio.com/) website.
7. From within RStudio, install `BiocManager` so we can pull down RGLab packages and their dependencies from `BioConductor`.
```{r}
install.packages("BiocManager")
```
8. Install the release versions of `flowCore`, `flowWorkspace` and `openCyto` from BioConductor:
```{r}
library(BiocManager)
install("flowCore")
install("flowWorkspace")
install("openCyto")
```
9. Install the development versions of these packages from GitHub:
```{r}
tryCatch(library(devtools), error = function(e){
  install.packages("devtools")
  library(devtools)
})
install_github("RGLab/flowCore")
install_github("RGLab/flowWorkspace")
install_github("RGLab/openCyto")
```
10. Install `CytoExploreRData` and `CytoExploreR` from GitHub:
```{r}
install_github("DillonHammill/CytoExploreRData")
install_github("DillonHammill/CytoExploreR")
```

**Comment by hally166** [comment]
`install_github` does not build the vignettes.  You should use the `build_vignette = TRUE` parameter to do this.  However when doing this the following error appears:
```
> devtools::install_github("DillonHammill/CytoExploreR", build_vignettes = TRUE)
Downloading GitHub repo DillonHammill/CytoExploreR@master
√  checking for file 'C:\Users\chall\AppData\Local\Temp\RtmpuEY3mn\remotes32489e6393d\DillonHammill-CytoExploreR-fefcea5/DESCRIPTION' (447ms)
-  preparing 'CytoExploreR': (2.2s)
√  checking DESCRIPTION meta-information ... 
-  installing the package to build vignettes (725ms)
E  creating vignettes (51.8s)
   --- re-building 'CytoExploreR-Compensation.Rmd' using rmarkdown
   --- finished re-building 'CytoExploreR-Compensation.Rmd'
   
   --- re-building 'CytoExploreR-Manual-Gating.Rmd' using rmarkdown
   --- finished re-building 'CytoExploreR-Manual-Gating.Rmd'
   
   --- re-building 'CytoExploreR-Transformations.Rmd' using rmarkdown
   --- finished re-building 'CytoExploreR-Transformations.Rmd'
   
   --- re-building 'CytoExploreR-Visualisations.Rmd' using rmarkdown
   Warning in get_engine(options$engine) :
     Unknown language engine 'e' (must be registered via knit_engines$set()).
   --- finished re-building 'CytoExploreR-Visualisations.Rmd'
   
   --- re-building 'CytoExploreR.Rmd' using rmarkdown
   Loading required package: flowCore
   Loading required package: flowWorkspace
   Warning: multiple methods tables found for 'plot'
   Warning: multiple methods tables found for 'plot'
   As part of improvements to flowWorkspace, some behavior of
   GatingSet objects has changed. For details, please read the section
   titled "The cytoframe and cytoset classes" in the package vignette:
   
     vignette("flowWorkspace-Introduction", "flowWorkspace")
   Loading required package: openCyto
   Warning: multiple methods tables found for 'plot'
   Warning: multiple methods tables found for 'plot'
   Warning: multiple methods tables found for 'plot'
   Quitting from lines 172-180 (CytoExploreR.Rmd) 
   Error: processing vignette 'CytoExploreR.Rmd' failed with diagnostics:
   3 arguments passed to .Internal(unlink) which requires 4
   --- failed re-building 'CytoExploreR.Rmd'
   
   SUMMARY: processing the following file failed:
     'CytoExploreR.Rmd'
   
   Error: Vignette re-building failed.
   Execution halted
Error: Failed to install 'CytoExploreR' from GitHub:
  System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr (last 10 lines):
E> Quitting from lines 172-180 (CytoExploreR.Rmd) 
E> Error: processing vignette 'CytoExploreR.Rmd' failed with diagnostics:
E> 3 arguments passed to .Internal(unlink) which requires 4
E> --- failed re-building 'CytoExploreR.Rmd'
E> 
E> SUMMARY: processing the following file failed:
E>   'CytoExploreR.Rmd'
E> 
E> Error: Vignette re-building failed.
E> Execution halted
```

**Comment by DillonHammill** [comment]
I will look into this, but all the vignettes are nicely formatted on the webite any way. Look under the Articles tab:
https://dillonhammill.github.io/CytoExploreR/

**Comment by hally166** [comment]
Hi Dillon,
You have added support for `openCyto.minEvents = -1`, but this is only available in the GitHub version of openCyto, not the bioCManager version. Installing as described causes the `cyto_setup` command to fail.

**Comment by DillonHammill** [comment]
Can you post the error in a new issue?

**Comment by hally166** [comment]
done, and it was the cyto_gate_draw command. I need to neaten up my notebook.

**Comment by DillonHammill** [comment]
Development versions of RGLab packages are no longer required for CytoExploreR, you now simply get the package binaries from BioConductor:
```{r}
# Install RGLab dependencies
BiocManager::install(c("flowCore", "flowWorkspace", "openCyto"))
```

Then install `CytoExploreRData` and `CytoExploreR`:
```{r}
devtools::install_github("DillonHammill/CytoExploreRData")
devtools::install_github("DillonHammill/CytoExploreR")
```
