### ISSUE TITLE
Images not rendered in Getting Started vignette

### ISSUE THREAD

**Issue by mblue9** [DillonHammill/CytoExploreR#120]
**Describe the bug**
Just to let you know none of the images in the Getting Started vignette have rendered. I built the pkgdown site for this repo locally and they all appear fine so maybe just a glitch with the build here? 

**To Reproduce**
See where images are supposed to be here https://dillonhammill.github.io/CytoExploreR/articles/CytoExploreR.html

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. mac, windows or linux]

**Additional context**

**Comment by DillonHammill** [comment]
Thanks for reporting this. pkgdown keeps setting the wrong paths to images in the docs folder. I will manually correct these today so that the images are displayed correctly.

**Comment by DillonHammill** [comment]
Done! The images should now appear on the website. I am not sure why pkgdown is getting all the image paths wrong - I will need to look into this at some point when I get some time.

**Comment by mblue9** [comment]
Great! Looks good. 

If you're building locally then pushing to Github maybe pkgdown is getting confused with the paths? You could use a Github Actions to auto-build e.g. here https://github.com/r-lib/actions/blob/master/examples/pkgdown.yaml
