### ISSUE TITLE
cyto_gate_draw in a shiny app

### ISSUE THREAD

**Issue by jsaintvanne** [DillonHammill/CytoExploreR#121]
Hi,
I'm actually using your function `cyto_gate_draw` and it works pretty well thanks !
But when I run it it open 2 R windows whereas I have only one with a picture where I must select my gate... And when it's done with my gate they do not closed... I just would like they close even if there are 2 windows it is not a problem 

Have you got experienced the same thing already ? Do you have a solution for that ?

Thanks !

**Comment by DillonHammill** [comment]
@jsaintvanne thanks for using CytoExploreR. I am not exactly sure what your problem is. Are you able to share code, screenshots or recording to demonstrate the problem in more detail so that I can take a closer look.

**Comment by jsaintvanne** [comment]
Thanks for this very fast answer !!

Here is where the function is used : 
```R
gate = tryCatch({
                            cyto_gate_draw(
                                cs_temp,
                                parent = input$parent_gate,
                                alias = c(input$gate_Name),
                                channels = c(input$xcol, input$ycol),
                                point_col = input$color_channel,
                                axes_limits = "auto")
                        }, invalid = function(i) NULL
                        ,error = function(e){
                        toastr_error("Error !", "You haven't drawn your gate")
                        return(error_status = list("type" = "error", "message" = err$message))
                    })
```

And here the 2 windows that opened when I run it : 
![image](https://user-images.githubusercontent.com/35449860/129719816-412d57a3-0d33-4f68-864e-ea06543b3794.png)

When I select my gate with left clic : 
![image](https://user-images.githubusercontent.com/35449860/129719933-c532bdfb-1221-477d-955d-3583acd938a6.png)

And when I right clicked and it completed the gate itself : 
![image](https://user-images.githubusercontent.com/35449860/129720007-b85d482f-985a-4eb1-ab6a-e583782ef82f.png)

And then it stays here... I just would like to close these windows and ask myself why there is 2 windows opened

Is it clearest for you ?

**Comment by DillonHammill** [comment]
Can you run `dev.off()` and run the code again. There should only be one window that opens, but it is fine to close both.

**Comment by DillonHammill** [comment]
Running `cyto_plot_reset()` will reset all `cyto_plot` related setting which may also fix the problem.

**Comment by jsaintvanne** [comment]
Hi !
Sorry I was not working on it since 2 days ! 
I tried with `dev.off()` after selected a gate and it works well to close my 2 windows (with 2 `dev.off()`) and I think I will use it for the moment... 
I will try the `cyto_plot_reset()` function and come back to say to you ! 
But this looks strange to have to do it and I don't really know why this is like this

Thanks a lot for your help for the moment ! And I hope I will find why it does it

**Comment by DillonHammill** [comment]
It is not designed to work in shiny so it is likely that shiny opens the extra device, in which case there isn't much you can do. Keep an eye out for the next version of CytoExploreR it is a significant upgrade which may resolve this issue.

**Comment by DillonHammill** [comment]
Closing this issue. please reopen if the issue persists with version 2.0.0 of CytoExploreR (coming soon).
