### ISSUE TITLE
cyto_gate_draw/cyto_gate_edit point drawing is very slow

### ISSUE THREAD

**Issue by humzalikhan** [DillonHammill/CytoExploreR#124]
**Briefly describe what you hope to achieve:**
- The cyto_gate_draw function is very slow, ie taking 5-15 seconds per point to be drawn in a polygon. I'm using an M1 Mac on Big Sur. Any tips?

**Outline the steps taken to attempt to reach this goal (paste code below):**
```{r}
setwd("~")
files <- list.files(path = "FOLDERPATH", full.names = TRUE)
fs <- read.ncdfFlowSet(files = files)

gs<-GatingSet(fs)

channels <- cyto_fluor_channels(gs)
trans <- estimateLogicle(gs[[1]], channels)
gs <- transform(gs, trans)

# gating ----
setwd("WD")

cyto_map(gs)

# gate drawing ----- 
cyto_gate_draw(gs,
          parent = "root",
          channels=c("Ir191Di","Ir193Di"),
          alias = "Ir+",
          type = "polygon",
          gatingTemplate = "XXX.csv",display=.1)
```

**Include any associated screenshots or images here:**

**Comment by humzalikhan** [comment]
Looks like there were too many cells! Changing display to .05 fixed it.

**Comment by DillonHammill** [comment]
Precisely! You can also use the select argument to pull events from only a subset of samples. FYI you will see about 5 times speed improvement in plotting in the new version of CytoExploreR (coming soon).

**Comment by humzalikhan** [comment]
Exciting! Thank you for your awesome work
