### ISSUE TITLE
Undefined column requested Error

### ISSUE THREAD

**Issue by rwbaer** [DillonHammill/CytoExploreR#126]
**Briefly describe what you hope to achieve:**
-I'm trying to apply a 2 channel compensation to a gating set

**Outline the steps taken to attempt to reach this goal (paste code below):**
The spill matrix was created in separate source file and save in Spillover-Matrix.csv

![spill](https://user-images.githubusercontent.com/3155051/141490182-871decc2-616f-4e1f-aa4f-2306c6059418.png)

I then created a gating set and tried to apply the compensation, but got an undefined column error that I don't understand.
 
```{r}
# load in data from "Samples" folder
gs <- cyto_setup("Samples",
                 gatingTemplate = "Samples-gating.csv")


# Show us what we have
cyto_channels(gs)
cyto_markers(gs)
cyto_fluor_channels(gs)

# Apply compensation
gs <- cyto_compensate(gs,
                      spillover = "Spillover-Matrix.csv")
```
The resulting console output and error is shown below.  Not sure where I'm going wrong.
**Include any associated screenshots or images here:**
![console](https://user-images.githubusercontent.com/3155051/141491674-dc24ade5-a375-43b4-9ace-04cf34afa278.png)

**Comment by DillonHammill** [comment]
@rwbaer, thanks for reporting this. Looks like a bug in `cyto_compensate()` - it is expecting your spillover matrix to contain all the flourescent channels in your samples. I will push a fix later today.

**Comment by DillonHammill** [comment]
@rwbaer, this should now be fixed.

Please pull down the latest version from GitHub and try again:
`devtools::install_github("DillonHammill/CytoExploreR")`

**Comment by rwbaer** [comment]
This seems to be working now.  Thanks.
