### ISSUE TITLE
cyto_gate_draw() - Does not show popup window in Rnotebook or markdown

### ISSUE THREAD

**Issue by northNomad** [DillonHammill/CytoExploreR#13]
As titled.

1. When using ```cyto_gate_draw()```
In console: gives a popup window for manual gating.
In script: gives a plot in plotting environment for manual gating.
In Rmd: nothing shows up and the code finishes running (ie, no red stop hexagon in console). 

2. If I have a ```gatingTemplate.csv```  and its corresponding .fcs files in a ```flowSet``` - 
How do I quickly reproduce the gating set?

ie)
```gs <- GatingSet(flowSet)```
How to quickly apply the ```gatingTemplate.csv``` on ```gs``` which currently only has node "root"? Which function do I use?

Regards,
NN

**Comment by DillonHammill** [comment]
@northNomad, `cyto_gate_draw` is used to initially draw the gate. If you already drawn the gate  it has been saved to the gatingTemplate. I comment out the `cyto_gate_draw` calls after running them (i.e. set eval = FALSE in Rmd). I would copy these lines and run them in the console directly, Rmd does not allow gating, it will just give a plot. FYI to include the plot in Rmd you can save the image after gating from the menu and then include that image in your Rmd.

To apply the gatingTemplate to your samples, load them in with `cyto_setup`, apply compensation with `cyto_compensate`, apply transformations using `cyto_transform` and then apply the gatingTemplate:

```{r}
cyto_gatingTemplate_apply(gs, "gatingTemplate.csv")
```
