### ISSUE TITLE
Channel Selector Dropdown dysfunction

### ISSUE THREAD

**Issue by rwbaer** [DillonHammill/CytoExploreR#130]
**Describe the bug**
When using cyto_spillover_compute(), the channel selector dropdown is not working properly, particularly on samples after the first one.  I'm pretty sure this used to work fine, but it has been dysfunctional for a while now.

**To Reproduce**
1. Run cyto_spillover_compute
2. Attempt to populate the channels for the bead standards
3. Note that the scrolling arrows don't produce the set of selection but are blank.
4. If you type in the channel names by hand, things work fine, FL2-AREA, FL3-AREA, etc.

**Expected behavior**
I expect the dropdown to show the available channels
![ChannelSelector](https://user-images.githubusercontent.com/3155051/150693879-b116c220-4d0b-4df5-9675-4e9da1eba328.png)

**Desktop (please complete the following information):**
 - OS: Window 11 shinny 1.7.1 shinnyjs 2.1.0

**Additional context**
As noted, the workaround is to simply type in the desired channel name for each file.

Interesting, I think TAB completion is working when filling in the blank channel fields.

**Comment by DillonHammill** [comment]
The dropdown works as expected there is just not enough space to display the options since your table is so small. You will need to make use of the autocomplete functionality here.
