### ISSUE TITLE
Plot not shown in Rshiny - Empty Plot

### ISSUE THREAD

**Issue by eudoraleer** [DillonHammill/CytoExploreR#132]
Hi,

I was trying to use cyto_plot() in rshiny and in local run, it works and the plots were shown. However, when I pushed it to shinyapps, it is not showing, just give a blank plot. Please assist me.

Best,
eudora

**Comment by DillonHammill** [comment]
@eudoraleer, do you have some code to share? It is difficult to help you without an example. `cyto_plot()` definitely works within shiny applications, you may need to set `popup = FALSE` to make sure tbe right graphics device is used.

**Comment by eudoraleer** [comment]
> @eudoraleer, do you have some code to share? It is difficult to help you without an example. `cyto_plot()` definitely works within shiny applications, you may need to set `popup = FALSE` to make sure the right graphics device is used.

Dear Dillon,

It is not working for me somehow, so what I did was I saved the plots to PNG and shown in RShiny:)

Best,
Lu

**Comment by DillonHammill** [comment]
I think this is fixed in the new version of CytoExploreR, I would give it another try once it is released.
