### ISSUE TITLE
shiny yeti theme error

### ISSUE THREAD

**Issue by rwbaer** [DillonHammill/CytoExploreR#137]
**Briefly describe what you hope to achieve:**
I'm trying to create a gating set with code that I'm pretty sure has worked in the past.  Something seems to have changed with shiny themes, but I was not even aware that we were using shiny themes.  Any insights on how to precede?  This happens on at least two different installations

**Outline the steps taken to attempt to reach this goal (paste code below):**
- Include all data preparation steps where appropriate.
```{r}
> library(CytoExploreR)
> gsSamp <- cyto_setup(path = "Samples",
+                  gatingTemplate = "Samples-Template.csv",
+                  details = "Samples-Details.csv",
+                  restrict = TRUE)
Loading FCS files into a GatingSet...
Assigning markers to channels...
Error in shinytheme("yeti") : 
  yeti is not an available theme. Valid themes are: .
```

**Include any associated screenshots or images here:**

**Comment by DillonHammill** [comment]
Please update your DataEditR package:
```{r}
install.packages("DataEditR")
```

I just realised I haven't fixed this in `cyto_spillover_edit()` too, I will get onto that today.

**Comment by rwbaer** [comment]
This alone did not seem to solve it.  I'm showing version 0.1.5 for DataEditR, if that is helpful.  

Same error as before and the list available themes is still just a dot, ".".

**Comment by DillonHammill** [comment]
Oh yeah, sorry I forgot that the current version doesn't use DataEditR yet. I will push a fix soon.

**Comment by rwbaer** [comment]
@DillonHammill thanks we seem to be  back up and running again.
