### ISSUE TITLE
It is possible extract the gated value to a csv?

### ISSUE THREAD

**Issue by ChenJiuu** [DillonHammill/CytoExploreR#139]
I want to extract the gated population(or events) of 100 files(may be to a csv file?) but don't know how to do it.

<img width="598" alt="image" src="https://user-images.githubusercontent.com/50128686/159681049-06b5ae49-1d16-42b8-a598-2dfa2996ccc5.png">

I'm now copying and pasting every value but very erratic.

Is there a convenient way to do that?

**Comment by DillonHammill** [comment]
Are you after the statistics or the events?

**Comment by DillonHammill** [comment]
```{r}
stats <- cyto_stats_compute(gs, parent = "Live Cells", alias = c("T Cells","B Cells"), stat = "freq")

write.csv(stats, "stats.csv")

**Comment by ChenJiuu** [comment]
Hi Dillon,
Thank you for your reply and your solution!
I found the Export Statistics section and I’m still exploring it.
By the way, thanks for the package, It saved me tons of time.

**Comment by simonuoft** [comment]
Hi, I have a follow up question on that. 
Is it possible to extract all the gated events as a csv file (or a data frame) with basically one line per cells and each column being a different marker ?
Thanks in advance

**Comment by DillonHammill** [comment]
There are some better APIs coming for this, but you can use `cyto_extract()` with `raw =TRUE` to pull out the events for each sample into a list. You can then loop through the list and write the data to CSV files.
```{r}
raw <- cyto_extract(gs, parent = "T Cells", raw = TRUE)
```
