### ISSUE TITLE
Rename cyto_gatingTemplate_apply() to cyto_gatingTemplate_load()

### ISSUE THREAD

**Issue by ChenJiuu** [DillonHammill/CytoExploreR#140]
I've been searching the documentation for a method that could load a saved gate to reproduce results.

I tried:
cyto_gate_edit
cyto_gate_extract
cyto_gatingTemplate_active
cyto_gatingTemplate_read
...so on

because those function names are very similar, it took a long journey getting to cyto_gatingTemplate_apply().

Personally, since reusing a saved gate is easily making me think that a function named "xxxxxx_load()" may exit, I think renaming _apply() to _load() may help with legibility.

I'd appreciate it if you could take this into consideration.

**Comment by DillonHammill** [comment]
A lot of thought has gone into the naming of functions within CytoExploreR. `cyto_gatingTemplate_apply()` correctly describes the purpose of the function - to apply a gatingTemplate to a GatingSet. The equivalent of loading a gatingTemplate is `cyto_gatingTemplate_read()`. In the new version (coming soon) there is also a `cyto_gate_apply()` function which applies gate objects to the GatingSet.
