### ISSUE TITLE
cyto_convert to collapse gating set

### ISSUE THREAD

**Issue by rwbaer** [DillonHammill/CytoExploreR#141]
**Briefly describe what you hope to achieve:**
I am attempting to automatically draw a quad gate based on all the samples in my gating set and add a node to the nodes I already created in CytoExploreR manually.  

I had intended to use gate_quad_sequential() from the openCyto package and then gs_pop_add from the flowworkspace package.

Since gate_quad_sequential() requires a flow frame I tried to use cyto_convert from CytoExploreR to collapse the gating set into a single flow frame, but I seem to end up with an empty flow frame.  Clearly, I'm doing something wrong.  I was expecting the result to based on root node.

Any suggestions on how to approach such a task?  What am I misunderstanding about cyto_convert?  

Code fragment below

**Outline the steps taken to attempt to reach this goal (paste code below):**
- Include all data preparation steps where appropriate.
```{r}
> # =======================================================
> # Automated approach to quad gate (capital letter gates)
> # -------------------------------------------------------
> # merge all samples into a single flowframe for autogating
> frAll = cyto_convert(gsSamp, return = 'flowFrame')
> summary(frAll)
        TIME_MSW TIME_LSW FSC-HEIGHT FSC-AREA FSC-WIDTH SSC-HEIGHT SSC-AREA
Min.          NA       NA         NA       NA        NA         NA       NA
1st Qu.       NA       NA         NA       NA        NA         NA       NA
Median        NA       NA         NA       NA        NA         NA       NA
Mean         NaN      NaN        NaN      NaN       NaN        NaN      NaN
3rd Qu.       NA       NA         NA       NA        NA         NA       NA
Max.          NA       NA         NA       NA        NA         NA       NA
        SSC-WIDTH FL2-AREA FL4-AREA
Min.           NA       NA       NA
1st Qu.        NA       NA       NA
Median         NA       NA       NA
Mean          NaN      NaN      NaN
3rd Qu.        NA       NA       NA
Max.           NA       NA       NA

> summary(gsSamp)
   Length     Class      Mode 
        5 GatingSet        S4 
> 
> # Produce a quad filter object
> qg = gate_quad_sequential(frAll, 
+                      channels = c("FL4-AREA", "FL2-AREA"), 
+                      gFunc = mindensity, 
+                      min = c(5e2, 5e2),
+                      max = c(1e6, 1e6))
Error in if (nrow(peaks) < 2) score <- 0 else score <- abs(diff(peaks[,  : 
  argument is of length zero
In addition: Warning message:
In .find_peaks(x, ..., num_peaks = 2) :
  At least 2 observations must be given in 'x' to find peaks.
> # Turn the quad filter object into 4 gating nodes
> # use capitalized gate names to stay unique
> gs_pop_add(gsSamp, gq, validityCheck = TRUE, 
+            names = c("Apoptotic", "Necrotic-Apoptotic", "Necrotic", "Live"))
Error in is(gate, "filter") : object 'gq' not found
```

**Include any associated screenshots or images here:**

**Comment by DillonHammill** [comment]
`cyto_convert()` was originally designed for internal use only - in fact it has been removed from the new version of CytoExploreR. You should not attempt to gate data at the level of a `cytoframe` or `cytoset`, you should instead use `cyto_gatingTemplate_edit()` to add new `openCyto` entries to the gatingTemplate or call `gs_add_gating_method()` and update the gatingTemplate manually afterwards.

Remember, within CytoExploreR, the gatingTemplate serves as a means of keeping track of all the gating changes made to your GatingSet - it is important that any gates applied to your samples have entries in the gatingTemplate.

**Comment by rwbaer** [comment]
@DillonHammill With your help, I think I am now beginning to understand  the philosophy behind integrating opencyto gates  with cyto_explorer.  This should open up more robust ways to analyze data.  Your contributions have been really important.  Thanks.
