### ISSUE TITLE
instruction for installation of protobuf are outdated

### ISSUE THREAD

**Issue by malcook** [DillonHammill/CytoExploreR#144]
**Briefly describe what you hope to achieve:**
Install CytoExporeR on windows machine to work with latest R 4.2.0 (under RStudio 2022.02.2 with Rtools 4.2)

**Outline the steps taken to attempt to reach this goal (paste code below):**
Following instructions at https://dillonhammill.github.io/CytoExploreR/index.html  is not possible

since the instructions referenced have for some reason [been removed](https://github.com/RGLab/RProtoBufLib/commit/5940177f7435fd98b3fc2ab619312047306e3b11)

Can you please advise me how to proceed?

**Comment by DillonHammill** [comment]
@malcook `protobuf` is now bundled with `cytolib` there is no longer a need to install it manually.

**Comment by malcook** [comment]
Great.  

I was able to complete install in fresh R/RStudio with the help of #119 (and your comment "GitHub versions of RGLab packages are no longer required. Either installation method is fine for RGLab packages but bioc_ver = "devel" is no longer necessary.")

You should probably want to change your instructions accordingly, possibly as follows

```
install.packages('markdown') # else vignette building fails.
install.packages("remotes")
install.packages("tidyverse") # or whatever portion you require - at least tibble
install.packages("devtools")
devtools::install_github("RGLab/cytoverse")
cytoverse::cytoverse_update(repo='github',branch='master',upgrades_approved=TRUE,build_manual=TRUE,build_vignettes=TRUE) # presumably from github since that is where cytoverse came from
```

Also, if it helps anyone, my install failed at this point:

```
...
* DONE (ggcyto)
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 403.
  API rate limit exceeded for 161.129.22.101. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

  Rate limit remaining: 0/60
  Rate limit reset at: 2022-04-29 19:37:40 UTC

  To increase your GitHub API rate limit
  - Use `usethis::create_github_token()` to create a Personal Access Token.
  - Use `usethis::edit_r_environ()` and add the token as `GITHUB_PAT`. 
 ```

Following the advice given allowed me to rerun `cytoverse_update` which proceeded until failing due to absence of `markdown` package (which I've added to above instructions allowing `cytoverse_update` to now complete.

However, absence of pdflatex resulted in multiple warnings `pdflatex not found! Not building PDF manual.`  So, you might want to advise users to run:
```
Sys.which("pdflatex")
```
and if it is undefined to [install MiKTeX](https://miktex.org/download) first (and then restart RStudio before proceeding with your package).

Also, during subsequent running of
```
# CytoExploreRData 
devtools::install_github("DillonHammill/CytoExploreRData")
# CytoExploreR 
devtools::install_github("DillonHammill/CytoExploreR")
```
I was repeatedly warned:
```
'\\ion\homedir$\mec\My Documents'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
```
Not sure if that really matters going forward...
