### ISSUE TITLE
cyto_gatingTemplate_edit Error

### ISSUE THREAD

**Issue by rwbaer** [DillonHammill/CytoExploreR#146]
**Briefly describe what you hope to achieve:**
I'm trying to use cyto_gatingTemplate_edit()  The editing itself seems to be going okay, but when I try to save the edited template I'm getting an error I don't understand.

It may be important to mention that I was trying to add an opencyto gate not a boolean or reference gate.  There were some blank cells that mirror those that appear blank on the opencyto examples, but I put NA in the ones that appear to require NA.

I would try using Excel as an alternative but putting '+/-' into a cell is made difficult by Excel's belief I'm trying to enter an improper formula.  :-(   

**Outline the steps taken to attempt to reach this goal (paste code below):**
Here's the error I'm getting:
```{r}
> cyto_gatingTemplate_edit(gsAuto)
Do not modify existing gatingTemplate entries!
Add new rows to add boolean or reference gates to the GatingSet.
Error in if (gm == "dummy") return(this_row) : 
  missing value where TRUE/FALSE needed
```

**Include any associated screenshots or images here:**

**Comment by DillonHammill** [comment]
Leave the NA cells empty and make sure you include the gatingMethod.

**Comment by rwbaer** [comment]
Okay, I have gotten this to work with some combination of pre-populating before using the editor, but I'm not quite convinced that it is working as robustly as intended.  Nevertheless, when it works it is very convenient.  

Thanks as always!  Your support is appreciated.
