### ISSUE TITLE
error installing

### ISSUE THREAD

**Issue by baj12** [DillonHammill/CytoExploreR#148]
**Describe the bug**
doesn't install

**To Reproduce**
R CMD INSTALL --no-multiarch --with-keep.source CytoExploreR

**Expected behavior**
An updated CytoExploreR

And by the way, thanks for all your great work!!!

**Screenshots**
```
* installing to library ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library’
* installing *source* package ‘CytoExploreR’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Warning message:
replacing previous import ‘flowViz::contour’ by ‘graphics::contour’ when loading ‘flowStats’ 
Error: object ‘CytoExploreR_.preprocess_row’ is not exported by 'namespace:openCyto'
Execution halted
ERROR: lazy loading failed for package ‘CytoExploreR’
* removing ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library/CytoExploreR’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library/CytoExploreR’
```

**Desktop (please complete the following information):**
 - OS: MAC

**Comment by baj12** [comment]
Just digging through the code and found that this is related to openCyto.
I am using openCyto_2.5.4

**Comment by DillonHammill** [comment]
You need to install my fork of openCyto:
```{r}
devtools::install_github("DillonHammill/CytoExploreR")
```

**Comment by baj12** [comment]
Yes that works. 
thanks,
maybe that could included in the install instructions.

**Comment by DillonHammill** [comment]
You should only need that for the `devel` version which has still matured enough for public release (currently undergoing extensive and frequent changes). You will need to stick to the `master` branch for now.
