### ISSUE TITLE
code problem (cyto_gateTemplate_apply)?

### ISSUE THREAD

**Issue by baj12** [DillonHammill/CytoExploreR#149]
**Describe the bug**
I am running into a problem with cyto_gateTemplate_apply and found a potential bug.
I.e. I would like to confirm with you that you really test for class gateTemplate and not gatingTemplate

line 227 and 251 in cyto_gateTemplate.R

```
    if(cyto_class(gateTemplate, "gateTemplate")) {
```

**Comment by DillonHammill** [comment]
`cyto_gateTemplate_apply()` is a new API introduced in version 2.0.0. Since this is not yet stable enough for public use I won't be supplying support for this. It is stable enough for use but you need to refer to the docs carefully - the changes, improvements and new features are extensive.
