### ISSUE TITLE
Specifying directory when creating new gatingTemplate?

### ISSUE THREAD

**Issue by northNomad** [DillonHammill/CytoExploreR#15]
Almost always - we're working with .fcs files stored in multiple directories. 
It makes sense to store the ```gatingTemplate.csv``` file of each gating set in their corresponding .fcs folder.

Currently, when we use ```cyto_gatingTemplate_create()```, the file is created in the current working directory. 
This is far from ideal because it doesn't make sense to store all the gatingTemplate.csv in one place.

Can we allow the function ```cyto_gatingTemplate_create()``` to take an additional argument so that we can specify the path that the .csv file should be created?

Regards,
NN

**Comment by DillonHammill** [comment]
@northNomad, just supply the path in the filename and it will create the gatingTemplate in that directory. For example, if I wanted to create a gatingTemplate in a folder called "Samples":
```{r}
cyto_gatingTemplate_create("Samples/gatingTemplate.csv")
```

However, I would not mix other files with your fcs files as it will cause problems with `cyto_setup()`. I will need to update `cyto_setup()` to ignore other file types when loading in the samples.

I will play around with it and see what I can do.

**Comment by northNomad** [comment]
Thanks for the clarification - 

Appreciate it lots.
NN

**Comment by DillonHammill** [comment]
@northNomad, for now you can manually exclude your gatingTemplate when running `cyto_setup`:
```{r}
cyto_setup("Samples",
                   exclude = "gatingTemplate.csv")
```
