### ISSUE TITLE
Docker for CytoExploreR v1.1.0

### ISSUE THREAD

**Issue by BojanaSm** [DillonHammill/CytoExploreR#153]
I am trying to create a Docker image for CytoExploreR v1.1.0. The installation seems OK. However, when I run the cyto_gate_draw function, and I mark a position within the plots window, the marked spot is always moved to the left and up. I tried pulling and running the dhammill/cytoexplorer: v1.1.0 docker, and I have had the same issue. On the other hand, when I pull dhammill/cytoexplorer: latest (it is CytoExploreR v1.0.8), it works well. 

I used the following code for testing: 

```{r}
library(CytoExploreRData)
library(CytoExploreR)
# Load in samples
fs <- Activation
gs <- GatingSet(fs)

# Apply compensation
gs <- compensate(gs, fs[[1]]@description$SPILL)

# Transform fluorescent channels
trans <- estimateLogicle(gs[[4]], cyto_fluor_channels(fs))
gs <- transform(gs, trans)

# Gate using cyto_gate_draw
gt_gating(Activation_gatingTemplate, gs)

# draw gates using cyto_gate_draw
cyto_gate_draw(gs,
               parent = "Dendritic Cells",
               channels = c("Alexa Fluor 488-A", "Alexa Fluor 700-A"),
               alias = c("CD8+ DC", "CD4+ DC"),
               gatingTemplate = "GatingTemplate.csv",
               type = "rectangle"
)
```
<img width="748" alt="Screenshot 2022-07-20 at 16 10 21" src="https://user-images.githubusercontent.com/109676722/180003775-1623f116-2170-456b-983a-6f6fc33458e2.png">

**Comment by DillonHammill** [comment]
I believe this issue is due to the zoom settings of your browser. If it is set to anything other than 100% the points don't seem to appear in the same location as the clicks.
