### ISSUE TITLE
Broken histograms?

### ISSUE THREAD

**Issue by th-of** [DillonHammill/CytoExploreR#154]
With my data I often get weird/broken histograms, anyone know what's causing this? Some examples below.
FCS 3.1 files exported from a MACSQuant Analyzer flow cytometer.

I load the files with 
`gs <- cyto_setup("FlowFiles", emptyValue=FALSE, gatingTemplate = "Manual-Gating.csv")`

I do a logicle transformation
`gs <- cyto_transform(gs, type = "logicle")`

Then plot
`figure <- cyto_plot(newgs, parent = NULL, channels = "FL2-A", ... , ... ,  ... )`

<img width="160" alt="Untitled picture 2" src="https://user-images.githubusercontent.com/46278528/182588802-7fb7bc53-19bf-4ae9-8ea5-a44c3951befd.png">
<img width="161" alt="Untitled picture" src="https://user-images.githubusercontent.com/46278528/182588817-e233e605-a230-427c-9e95-9fae57f5bbd0.png">
<img width="349" alt="Untitled" src="https://user-images.githubusercontent.com/46278528/182590047-f0a960d3-368b-49e4-93d0-8b955fbc19c7.png">

**Comment by DillonHammill** [comment]
@th-of this is a known bug in CytoExploreR which has been fixed in the soon to be released version 2.0.0. I would recommend updating when it becomes available. In the meantime you may need to use ggcyto to plot your histograms.
