### ISSUE TITLE
Cyto_gate_draw() overlay labeling and coloring

### ISSUE THREAD

**Issue by kim619** [DillonHammill/CytoExploreR#161]
Hi Dillon,

I am working on overlaying gated populations onto another using cyto_gate_draw() function, though it does not seems to show the overlay population legend nor I couldn't find the color changing command in the vignettes. I wonder if you can give me some insights on doing them. 

For example, I want to compare the two channels' output in the same population: so I want to have the overlaying population to be slightly transparent so I can visualize the other population. 

`cyto_gate_draw(gs1,parent="R6 GFP+RFP Pi",
               alias = "R6 GFP+RFP Pi_GFPonly1",
               channels = c("FITC-H"),
               select="05-Well-A1.fcs",
               type="interval",
               gatingTemplate="GatingTemplate4.csv",
               plot=TRUE,
               axes_limits="data",
               popup=FALSE)
               legend_text=c("R6 GFP+RFP pi GFP only","R6 GFP+RFP pi RFP only"),
               overlay=c(R6_GFP_RFP_Pi_RFPonly))`

<img width="582" alt="Screen Shot 2022-09-07 at 15 30 45" src="https://user-images.githubusercontent.com/66120425/188994923-86c4dd5c-2ffc-4a4d-a94a-8036c066965a.png">

Thanks in advance.

**Comment by DillonHammill** [comment]
Legends are turned off in `cyto_gate_draw()`. I would recommend supplying the colours for each layer manually through `point_col` so you can keep track of things. The `parent` is always at the back and `overlay` on top.

**Comment by kim619** [comment]
I got the coloring scheme now, but I fail to turn on the legend.

Example:
`> cyto_gate_edit(gs1,parent="root",
+                alias = "R6 GFP+RFP Pi",
+                channels = c("FITC-H","PE-H"),
+                select="05-Well-A1.fcs",
+                type="rectangle",
+                legend=TRUE,
+                gatingTemplate="GatingTemplate4.csv",
+                plot=TRUE,
+                axes_limits="data",
+                popup=FALSE)
Error in cyto_plot.flowFrame(fr_list[[y]][[1]], channels = channels, overlay = fr_list[[y]][seq_along(fr_list[[y]])[-1]],  : 
  formal argument "legend" matched by multiple actual arguments`

**Comment by DillonHammill** [comment]
You can't use the legend, it is turned off internally.

**Comment by kim619** [comment]
Oh I see, so from the main page of the cytoexploreR package: I saw this gating scheme with the color legend on the side, is it manually added without R?


<img width="653" alt="Screen Shot 2022-09-07 at 17 01 19" src="https://user-images.githubusercontent.com/66120425/189005451-9eac319b-49f9-4b3d-8bc5-d91fd6af4aa6.png">

**Comment by DillonHammill** [comment]
Those are separate functions, `cyto_gate_draw()` is purely there to allow you to draw the gates. For more sophisticated visualisations look at `cyto_plot()` and `cyto_plot_gating_scheme()` as depicted above.

https://dillonhammill.github.io/CytoExploreR/articles/CytoExploreR-Visualisations.html

**Comment by kim619** [comment]
Sounds good, thanks as always!
