### ISSUE TITLE
Selecting non-consecutive subset of data for cyto_plot

### ISSUE THREAD

**Issue by kim619** [DillonHammill/CytoExploreR#163]
Hi, I wonder if we can select non-consecutive data for cyto_plot () function:

Example: I tried the [1:3] - which means selecting 1 to 3, though I only want 1 and 3, excluding 2, how should I achieve that? seems like [1,3] nor <-c(1,3) does not work. 
```
cyto_plot(gs1[1:3],
          parent="root",
          channels="PE-H",
          density_stack=0.5,
          density_cols = c("green","blue","pink"),
          density_fill_alpha = c(0.4,0.4,0.4),
          label_stat=rep("median",3),
          label_text_col="black",
          label_text = c("R6 GFP+RFP Pi",
                         "R13b GFP+RFP Pi",
                         "R6 GFP+RFP Px"),
          label_fill="white",
          label_fill_alpha=0.6,
          title = "R6 GFP+RFP cells")
```

<img width="723" alt="Screen Shot 2022-09-10 at 23 38 18" src="https://user-images.githubusercontent.com/66120425/189515537-88453c7e-631a-4eb9-a526-b8d628568eec.png">

Thanks!

**Comment by DillonHammill** [comment]
gs[c(1,3)]
