### ISSUE TITLE
cyto_save values

### ISSUE THREAD

**Issue by jaredmychal** [DillonHammill/CytoExploreR#169]
Hi Dillon,
This is more of a question as opposed to issue. When saving a gating set to .fcs, do the transformed values get written or do the original values get written?

Example, would this export the arcsinh transformed values:

# Setup Activation samples
gs <- cyto_setup("~/Diana CyTOF Nov 2022/Blood/data/compensated",
                 gatingTemplate = "Manual-Gating.csv")

gs <- cyto_transform(gs, type = "arcsinh")

cyto_gate_draw(gs,
               alias = "Cells",
               channels = c("Ce140Di","Ir191Di"),
               type = "rectangle", axes_trans = trans )

cyto_save(gs, parent = "Cells", save_as = "~/data/cells")

**Comment by DillonHammill** [comment]
Yes that is correct. You can write the linear data by setting `inverse =TRUE` in `cyto_save()`.

**Comment by jaredmychal** [comment]
Excellent, thank you!
