### ISSUE TITLE
unused argument (openCyto.minEvents = -1) error

### ISSUE THREAD

**Issue by hally166** [DillonHammill/CytoExploreR#17]
Hi Dillon,
You have added support for openCyto.minEvents = -1, but this is only available in the GitHub version of openCyto, not the bioCManager devel version. Installing as described in your documentation causes the cyto_gate_draw command to fail. Using the GitHub master of openCyto works.
The error I get is (which I also get with my own data):
```
> cyto_gate_draw(gs,
+                parent = "root",
+                alias = "Cells",
+                channels = c("FSC-A", "SSC-A"))
Select at least 3 points to construct a polygon gate around the Cells population. 

Adding newly constructed gate(s) to Compensation-gatingTemplate.csv .
...
Error in (function (fs, pp_res, gFunc, popAlias, channels, gFunc_args)  : 
  failed at Compensation-7AAD.fcs
Error in .cyto_gate_draw(fr = new("flowFrame", exprs = structure(c(14539,  : 
  unused argument (openCyto.minEvents = -1)
```
I initially thought it was to do with the $FIL (or Tube Name) and filename not matching, but I changed the keywords using flowCore and the error still occurred.

**Comment by DillonHammill** [comment]
That makes more sense! Yes I think this change may not be reflected in the BioC build yet.

**Comment by jacobpwagner** [comment]
Hmm, by the last commit hash, Bioconductor shows that it should have https://github.com/RGLab/openCyto/commit/c4afb3ad5109d27a382a06d7d3be3e463399c0f3, and it passed its checks, so it should be in the newest available binary. Looking in to it now.

**Comment by jacobpwagner** [comment]
Sure enough when I install from BioC devel, the commit is not yet there. It could just be a delay on Bioconductor's end, but I added a version bump after some more recent changes just to be safe. So hopefully this should be included sometime in the next few days.

**Comment by DillonHammill** [comment]
Thanks @jacobpwagner!

**Comment by DillonHammill** [comment]
This should now be resolved, I will add the updated openCyto version to the dependencies.
