### ISSUE TITLE
Error when trying to install cytoverse packages

### ISSUE THREAD

**Issue by ghar1821** [DillonHammill/CytoExploreR#179]
**Describe the bug**
Cannot install cytoverse using `cytoinstaller::install_cyto(bioc_ver = "devel")`, as specified in the installation guide.

I cannot install cytoverse using the cytoinstaller package. I'm not quite sure why cytoverse is required as when I tried to install CytoExploreR, it only requires me to install `opencyto` from Bioconductor, which I managed to do.

**To Reproduce**
Run the command `cytoinstaller::install_cyto(bioc_ver = "devel")`. Instead of having cytoverse installed, the following error came up:

```
Error in cyto_pkg_github_url(pkg, owner, ...) : 
  Error in gh_process_response(raw) : 
  GitHub API error (404): Not Found
✖ URL not found: <https://api.github.com/repos/RGLab/COMPASS/releases/tags/bioc_3.17>
ℹ Read more at <https://docs.github.com/rest/reference/repos#get-a-release-by-tag-name>
```

**Screenshots**
<img width="633" alt="image" src="https://user-images.githubusercontent.com/5366317/227079349-0c17caec-2404-48f2-9167-246322f252e4.png">

**Desktop (please complete the following information):**
Mac. R 4.2.2 arm64

**Comment by DillonHammill** [comment]
All `cytoverse` packages including `cytolib`, `flowCore`, `flwoWorkspace` and `openCyto` are dependencies of `CytoExploreR`. You can simply install them from `BioC` now - development versions from GitHub are no longer required. 
```{r}
BiocManager::install(c("cytolib", "flowCore", "openCyto", "flowWorkspace"))
```

**Comment by ghar1821** [comment]
I see. Thanks @DillonHammill. Looking forward to v2.0!
