### ISSUE TITLE
Event count ("Cell count") for the y-axis in histogram plots?

### ISSUE THREAD

**Issue by th-of** [DillonHammill/CytoExploreR#181]
Using cyto_plot with 1D data I get % of Mode (normalized cell count) as the y-axis (scale 0-100). Setting density_modal = FALSE gives me a scale from 0 to ~1.7.

I want to get a y-axis like in the image below, is this possible using CytoExploreR?

![image](https://user-images.githubusercontent.com/46278528/227490614-bbd3655c-1b54-44e8-b734-a8f1bed26851.png)

**Comment by DillonHammill** [comment]
Not supported in the current version, but coming to CytoExploreR version 2.0.0!
