### ISSUE TITLE
cyto_setup details argument

### ISSUE THREAD

**Issue by rwbaer** [DillonHammill/CytoExploreR#183]
**Describe the bug**
During cyto_setup(), I tried to place "sample details" one folder layer up from where the script code (project directory) was set.  In terms of writing a sample-details.csv file this seems to work fine, but if "sample-details.csv" already existis cyto_setup() seems to not find it and pre-populate the columns with existing values.

**To Reproduce**
This code did not work to repopulate when "../FCSSamples-Details.csv" already exists
```{r}
gsSamp <- cyto_setup(path = "../Samples",
                     gatingTemplate = "../FCSVersion-Template.csv",
                     details = "../FCSSamples-Details.csv",
                     restrict = TRUE)
```

**Expected behavior**
I expect this to find an exiting "FCSSamples-Details.csv" in the parent directory if one exists, but instead it just has a single column containing the filelist from ../Samples.   If I hit Save it writes over the existing "../FCSSamples-Details.csv", so the problem seems confined just to the read portion of the operation.

**Desktop (please complete the following information):**
Windows 11 
platform       x86_64-w64-mingw32               
arch           x86_64                           
os             mingw32                          
crt            ucrt                             
system         x86_64, mingw32                  
status                                          
major          4                                
minor          2.3                              
year           2023                             
month          03                               
day            15                               
svn rev        83980                            
language       R                                
version.string R version 4.2.3 (2023-03-15 ucrt)
nickname       Shortstop Beagle  

**Additional context**

**Comment by DillonHammill** [comment]
The file name must contain "Experiment-Details.csv" in order for it to be automatically imported.
