### ISSUE TITLE
Guidance on Editing Compensation Matrix from FACS DIVA pre-compensated FCS Files

### ISSUE THREAD

**Issue by tiagobrc** [DillonHammill/CytoExploreR#191]
Issue Description:

Hello @DillonHammill,

I have been using your R package for flow cytometry data analysis and have encountered some challenges related to the compensation matrix when dealing with already compensated FCS files.

Briefly describe what you hope to achieve:

I would like to extract the compensation matrix from FCS files. Or do I have to export uncompensated data? 
I aim to edit this compensation matrix if necessary.

Outline the steps taken to attempt to reach this goal:

While the package documentation provides a general understanding of flow cytometry analysis, I couldn't find explicit steps or methods for dealing with the compensation matrix when using pre-compensated FCS files. 

Running the package works just fine but I would like to tweak the matrix. 

Best regards,

Tiago

**Comment by DillonHammill** [comment]
`cyto_spillover_edit()` will automatically extract the spillover matrix from your samples if it isn't supplied manually to `spillover`.

**Comment by tiagobrc** [comment]
This is helpful! Thanks!
