### ISSUE TITLE
cyto_plot computed stats look off

### ISSUE THREAD

**Issue by Biomiha** [DillonHammill/CytoExploreR#201]
Hi Dillon,

I've noticed that the stats that are plotted with `cyto_plot` don't actually correspond to the stats obtained by `cyto_stats_compute` for the same gates. 
I've used the prebundled GatingSet that comes with `flowWorkspace` as a test:

    library(flowWorkspace)
    dataDir <- system.file("extdata",package="flowWorkspaceData")
    gs_archive <- list.files(dataDir, pattern = "gs_bcell_auto",full = TRUE)
    gs <- load_gs(gs_archive)
    
    cyto_plot(gs, parent = "Live", alias = "CD19", channels = c("CD19", "CD3"))
    
    # Contrast this to ggcyto
    autoplot(gs, gate = "CD19", bins = 128)
    
   
    # The computed values correspond to the ones plotted by ggcyto
    cyto_stats_compute(x = gs, parent = "Live", alias = "CD19", stat = "percent")

![image](https://github.com/DillonHammill/CytoExploreR/assets/29175188/15409216-3a69-4155-a89b-20aa0d9b38b9)
![image](https://github.com/DillonHammill/CytoExploreR/assets/29175188/b2b304d5-a9a0-4a04-ab9e-649445401db0)

Any idea why the stats computation within `cyto_plot` looks a bit off?
Thanks

**Comment by DillonHammill** [comment]
`cyto_plot()` down samples to 50000 events by default so the stats will vary slightly. The stats should be the same if you set `events =1` to display all the events.
