### ISSUE TITLE
Automatic gating in CytoExploreR

### ISSUE THREAD

**Issue by MikhaelManurung** [DillonHammill/CytoExploreR#21]
Hi Dillon,

How can I do automatic gating within the `cyto_gate_draw` function?

Or is there any method equivalent to the CytoRSuite's implementation?
```
template <- rbind(template, app_pop(gs,
                                    alias = "T Cells",
                                    pop = "+",
                                    parent = "Live Cells",
                                    dims = "APC-Cy7-A,PE-A",
                                    gating_method = "flowClust",
                                    gating_args = "K=3,target=c(0,3)"))
```

Best,
Mikhael

**Comment by DillonHammill** [comment]
Hi Mikhael,

Yes this method still works. But now you can use `cyto_gatingTemplate_edit` to interactively add entries into the gatingTemplate. The gates will automatically be applied to the samples when the table editor is closed. Just supply your GatingSet and gatingTemplate:
```{r}
gs <- cyto_gatingTemplate_edit(gs, "gatingTemplate.csv")
```
