### ISSUE TITLE
Saving FCS files after transformation for a flowset by cyto_transformer_biex

### ISSUE THREAD

**Issue by Shuaiwei-Wang** [DillonHammill/CytoExploreR#217]
Hi,

How to save fcs. files after transforming data in a flowset into biex?

**Comment by DillonHammill** [comment]
For Gatingsets:
`cyto_save(gs, parent = "Live Cells")`

For cytoset:
`cyto_save(cs)`

See `?cyto_save` for details.

**Comment by Shuaiwei-Wang** [comment]
> For Gatingsets: `cyto_save(gs, parent = "Live Cells")`
> 
> For cytoset: `cyto_save(cs)`
> 
> See `?cyto_save` for details.

Thank you for the quick reply.

By using: 
## S3 method for class 'flowSet':

trans_biex <- cyto_transformer_biex(fcs_data)
cyto_save(trans_biex,
  save_as = "Transformed_back",
  inverse = FALSE,
  trans = NULL)


Got the error as following:
Error in UseMethod("cyto_save") : no applicable method for 'cyto_save' applied to an object of class "c('transformerList', 'list')"

**Comment by DillonHammill** [comment]
`tranaformer_biex()` just computes the transformation. You need to apply them using `cyto_transform()`:
`fs <- cyto_transform(fs, trans = biex_trans)`

Then you can write to new FCS files using `cyto_save()`.

**Comment by Shuaiwei-Wang** [comment]
> `fcw_data <- cyto_transform(fcs_data, trans = trans_biex)`

Thank you so much. It works.
