### ISSUE TITLE
Copying gate definition across samples

### ISSUE THREAD

**Issue by rwbaer** [DillonHammill/CytoExploreR#218]
**Briefly describe what you hope to achieve:**
As an example, I would like to use sample 10 of the activation data to define live and dead cells and then pass those gates to the other samples in the gating set. Currently, the node you define only exists for the sample(s) you use to define it.

Because of the way things work, if I define a gate for gsSamp[10], it will not exist for other subsets 1:9 or 11:32.  How does one work around this?

Occasionally, one might want to do this the other way around and define a generic gate for all samples and then revise the gate for only a single gate in the set.  I think FCSExpress software calls these sorts of gates "data specific gates"

**Outline the steps taken to attempt to reach this goal (paste code below):**
Here's the hypothetical code I used to do this with the activation set
```{r}
library(CytoExploreRData)
library(CytoExploreR)

# Activation FCS Files
cyto_save(Activation,
          save_as = "Activation-Samples")



# Setup Activation samples
gsSamp <- cyto_setup("Activation-Samples",
                 gatingTemplate = "Activation-gatingTemplate.csv")

# Apply compensation
gsSamp <- cyto_compensate(gsSamp, select = NULL)

# Transform fluorescent channels
trans <- cyto_transformer_logicle(gsSamp)
gsSamp <- cyto_transform(gsSamp,
                     trans = trans)

# Gate Cells
cyto_gate_draw(gsSamp,
               parent = "root",
               alias = "Cells",
               channels = c("FSC-A","SSC-A"))

# Gate Single Cells
cyto_gate_draw(gsSamp,
               parent = "Cells",
               alias = "Single Cells",
               channels = c("FSC-A", "FSC-H"))

# Run the following if gates already saved
cyto_gatingTemplate_apply(gsSamp, "Activation-gatingTemplate.csv")


cyto_plot_gating_tree(gsSamp)
cyto_channels(gsSamp)

# Now add an interval gate using all samples
cyto_gate_draw(gsSamp,
               parent = "Single Cells",
               alias = c("Live", "Dead"),
               channels = "7-AAD-A" ,
               type = "interval",
               negate = TRUE)

# Now add an interval gate using just sample 10
cyto_gate_draw(gsSamp[10],
               parent = "Single Cells",
               alias = c("Live10", "Dead10"),
               channels = "7-AAD-A" ,
               type = "interval",
               negate = TRUE)

# Draw 33 graphs of 2 gates each
cyto_plot_gating_scheme(gsSamp)


cyto_plot_gating_tree(gsSamp[10])
cyto_plot_gating_tree(gsSamp)
cyto_plot_gating_tree(gsSamp[10])
cyto_nodes(gsSamp)

```

**Include any associated screenshots or images here:**
notice it is much easier to guess where the live-dead cutoff is from samples like 10 than it is from the aggregate histogram.

cyto_plot_gating_scheme(gsSamp[[10]]) lets me compare the two interval gates on this sample, but none of the other samples show the consequences of choosing the interval based on sample 10 alone

![image](https://github.com/user-attachments/assets/6b3d6c12-3fec-4dce-9c2f-9ab40201dedb)
![image](https://github.com/user-attachments/assets/27f2b9b2-b0fc-42ad-a239-a8e73c3e0d8f)

Are there functions that will let me "work with"/modify/copy/apply gates across samples?

ADDENDUM
If after creating a gate for just one sample (here Live10 and Dead10), and one runs gate removal code
```{r}
cyto_gate_remove(gsSamp,
               parent = "Single Cells",
               alias = c("Live", "Dead"),
               channels = "7-AAD-A" ,
               type = "interval",
               negate = TRUE)
```
**you get an error:**
Error in FUN(X[[i]], ...) : Live10 does not exist in this GatingSet!

**Comment by djhammill** [comment]
See the `select` argument in `cyto_gate_draw()`, that is the correct way to select a subset of samples to display while gating and then automatically apply those gates to all samples.

If you need different gates for different samples, you need to add a new variable to `cyto_details()` and then pass it to `merge_by` in `cyto_gate_draw()`.

**Comment by rwbaer** [comment]
Thanks. So much to understand in this great plugin!!
