### ISSUE TITLE
Install CytoExploreR R Release (>=3.5)

### ISSUE THREAD

**Issue by DillonHammill** [DillonHammill/CytoExploreR#25]
Some of you Windows users may experience issues installing CytoExploreR on R-devel as the development version of Rtools (Rtools40) is required for Rhdf5lib. I do not recommend using Rtools40 yet as it may impact the installation of other packages. In this case I would recommend installing on your current R version by following these instructions:

**Install CytoExploreR on Windows R >= 3.5**
1. Install the release version of [R](https://cran.r-project.org/bin/windows/base/).
2. Install Rtools35 from this [link](https://cran.r-project.org/bin/windows/Rtools/). Make sure you select the option to add Rtools to your system PATH.
3. Install the latest version of [RStudio](https://rstudio.com/products/rstudio/download/).
4. Download and extract `protobuf` and `libxml2` from this [link](https://github.com/RGLab/RProtoBufLib/blob/master/INSTALL).
5. Extract both of these to C:\ (i.e. right click>Extract All>C:\).
6. In the search bar type environment and select "Edit the system environment variables". In the bottom section select "New" and set LIB_XML2 and C:/libxml2 (must be a forward slash here) and hit "OK". Then click "New" to add the protobuf environment variable LIB_PROTOBUF and C:/protobuf (must be a forward slash here) and hit "OK". Click "Apply" and then "OK" to save the new variables. **RESTART YOUR COMPUTER**.
7. From within RStudio run the following to get  `BiocManager` to install packages from BioConductor:
```{r}
if (!requireNamespace("BiocManager", quietly=TRUE)){
    install.packages("BiocManager")
}
```
8. Install the `release` versions of the RGLab packages on BioConductor in a step-wise manner. If any pop-ups ask if you would like to install from source select YES.
```{r}
library(BiocManager)
install("flowCore")
install("flowWorkspace")
install("openCyto")
```
9. Install the development versions of these packages from GitHub:
```{
tryCatch(library(devtools), error = function(e){
  install.packages("devtools")
  library(devtools)
})
devtools::install_github("RGLab/RProtoBufLib")
devtools::install_github("RGLab/cytolib")
devtools::install_github("RGLab/flowCore")
devtools::install_github("RGLab/flowWorkspace")
devtools::install_github("RGLab/flowStats")
devtools::install_github("RGLab/openCyto")
}
```
10. Install `CytoExploreRData` and `CytoExploreR` from GitHub:
```{r}
devtools::install_github("DillonHammill/CytoExploreRData")
devtools::install_github("DillonHammill/CytoExploreR")
```

**Comment by DillonHammill** [comment]
@stefankolling, with the devel version of BioC becoming the release version next month, the RGLab is hard at work getting their packages ready for this change. During this period, I suspect that there will be a lot of changes made that may temporarily impact your ability to do certain tasks.

I would recommend back tracking to older versions of these packages where things work more reliably. Here are the updated installation instructions for CytoExploreR that include the oldest possible versions of these packages for CytoExploreR to work correctly:
```{r}
# Remove all RGLab dependencies
remove.packages(c("RProtoBufLib", "cytolib", "flowCore", "flowWorkspace", "flowStats", "openCyto"))

# Install required versions of RGLab dependencies (BioC release + GItHub)
install.packages('BiocManager')
BiocManager::install('flowCore')
BiocManager::install('CytoML')
BiocManager::install('flowWorkspace')
BiocManager::install('openCyto')
remotes::install_github('RGLab/RProtoBufLib@ce730aaf6613694aaff06df19dbee8448d379a73')
remotes::install_github('RGLab/cytolib@3d4045b15e86bdffb776b26e060fc5046180c4c5')
remotes::install_github('RGLab/flowCore@cd4446e9cf3c4e567829dc42773e323a18243b92')
remotes::install_github('RGLab/flowWorkspace@7a72eed6d90d67098be3676378c241a411267557')
remotes::install_github('RGLab/flowStats@f4e2acdd8a6bfab06d372529a6f79fd8ec6b3085')
remotes::install_github('RGLab/openCyto@c4afb3ad5109d27a382a06d7d3be3e463399c0f3')
remotes::install_github('DillonHammill/CytoExploreRData')
remotes::install_github('DillonHammill/CytoExploreR')
```

Make sure that you run these installations line-by-line in case any errors pop up.

This exactly how the docker image has been set up, so this will get all CytoExploreR users using the same versions of these packages. These instructions should work for R4.0 as well, just make sure that you use the release version of `BiocManager`.

I will update the README with these instructions today.

**Comment by stefankolling** [comment]
@DillonHammill Thanks heaps! I backtracked to the older versions following your instructions step by step, but unfortunately R still crashes when calling flowjo_to_gatingset() of the CytoML package. At this point, I got curious and set up your docker image to check if it works there. Surprisingly, when I use RStudio in docker and run `library(CytoML)`, the R session immediately crashes (this does not occur on my local installation). Now I'm a bit confused as I suppose this doesn't happen for you, but at the same time I left the docker image untouched. I will try to understand what is going on and keep you posted.

**Comment by DillonHammill** [comment]
Development versions of RGLab packages are no longer required for CytoExploreR, you now simply get the package binaries from BioConductor:
```{r}
# Install RGLab dependencies
BiocManager::install(c("flowCore", "flowWorkspace", "openCyto"))
```

Then install `CytoExploreRData` and `CytoExploreR`:
```{r}
devtools::install_github("DillonHammill/CytoExploreRData")
devtools::install_github("DillonHammill/CytoExploreR")
```
