### ISSUE TITLE
This operation is supported only when you are connected to the server.

### ISSUE THREAD

**Issue by algebio** [DillonHammill/CytoExploreR#34]
Hi 

I'm trying to connect through Docker following the steps on Issue #22. I've done it before and I didn't have any issue. I have checked that I have the container using docker container ls but this time, when I do localhost:8787 I'm getting this message: This operation is supported only when you are connected to the server.

Probably it's something obvious that I'm missing but I can't see what. 

Regards
Juan

**Comment by DillonHammill** [comment]
@algebio, can you paste the output of the following:
```{r}
docker container ls
```
What OS are you running the container on?

**Comment by algebio** [comment]
Hi
I use Windows 10

H:\>docker container ls
CONTAINER ID        IMAGE                   COMMAND             CREATED             STATUS              PORTS                    NAMES
a70ab051c9f1        dhammill/cytoexplorer   "/init"             23 seconds ago      Up 22 seconds       0.0.0.0:8787->8787/tcp   magical_agnesi

**Comment by DillonHammill** [comment]
Have you tried replacing localhost with `127.0.0.1`? Was the `localhost:8787` working before for you?

**Comment by algebio** [comment]
H:\>localhost:127.0.0.1
This operation is supported only when you are connected to the server.

localhost:8787 was working fine last time I tried (about 2 weeks ago)

**Comment by DillonHammill** [comment]
Sorry I meant `127.0.0.1:8787`

**Comment by algebio** [comment]
H:\>localhost:127.0.0.1:8787
This operation is supported only when you are connected to the server.

H:\>127.0.0.1:8787
This operation is supported only when you are connected to the server.

**Comment by DillonHammill** [comment]
And that is in a browser right?

**Comment by algebio** [comment]
No, that was the command prompt (I knew this was going to end up in a very embarrassing way). I just tried on a browser and works fine. Thank you for your help and sorry for wasting your time. I need to sleep more.

**Comment by DillonHammill** [comment]
No problem, glad that you got it working. That is the only thing to run in the browser, everything else in the instructions is run from the command prompt.
