### ISSUE TITLE
Error using cyto_markers_edit with custom marker details file

### ISSUE THREAD

**Issue by Biomiha** [DillonHammill/CytoExploreR#36]
Hi Dillon,

I seem to be getting an error in v 1.0.6. if I try to either use cyto_setup or cyto_markers_edit by providing a new path name for the file to save the details to. 

    cyto_markers_edit(gs, file = "T_cell_marker_details.csv")

I get:

Error in dt[, c("name", "desc")] : 
  object of type 'closure' is not subsettable

**Comment by DillonHammill** [comment]
@Biomiha, can you please include a screenshot of editor if it opens? I would also recommend an update to v1.0.7 when you get time, it includes some important bug fixes.

**Comment by Biomiha** [comment]
@DillonHammill the editor doesn't open at all. I'll update and let you know.

**Comment by DillonHammill** [comment]
I do see the same error on v1.0.7. I will work on a fix now.

**Comment by DillonHammill** [comment]
Thanks for reporting @Biomiha, there was in fact a lingering typo in `cyto_markers_edit()`. This should now be fixed. Please install the latest version of CytoExploreR and try again:
```{r}
devtools::install_github("DillonHammill/CytoExploreR")
```

I will double check to make sure that I did not make the same error in `cyto_details_edit()`.

**Comment by DillonHammill** [comment]
`cyto_details_edit()` works as expected.

**Comment by Biomiha** [comment]
Thanks @DillonHammill. This now works as expected.
