### ISSUE TITLE
Cannot make factor levels in cyto_details()

### ISSUE THREAD

**Issue by northNomad** [DillonHammill/CytoExploreR#42]
Hi,

When using ```cyto_plot``` with the ```group_by``` argument, it is almost always desired to re-level the grouping factors so the plots are in the correct order.

However, when I do 
```
cyto_details(gs)$treatment <- c("DMSO", "DrugA", "DrugB") %>% rep(each = 3) %>% as.factor()
```
```
cyto_details(gs)$treatment %>% class()
> character

cyto_details(gs) %>% class()
>data.frame
```

Many thanks in advance,
NN

**Comment by DillonHammill** [comment]
@northNomad, unfortunately yiu cannot set factor levels for `cyto_details()` anymore. Instead you need to supply the desired levels within `cyto_plot()`:

```{r}

cyto_plot(gs,
parent = "root",
alias = "Cells",
channels = c("FSC-A","SSC-A"),
group_by = list(Treatment = c("DMSO", "DrugA", "DrugB"))
```

**Comment by northNomad** [comment]
Thanks for the pointer!
