### ISSUE TITLE
Error in plot.new() : figure margins too large

### ISSUE THREAD

**Issue by rwbaer** [DillonHammill/CytoExploreR#45]
**Briefly describe what you hope to achieve:**
Replicating the Getting Started vignette.

**Outline the steps taken to attempt to reach this goal (paste code below):**
```{r}
> # Visualise uncompensated data
> cyto_plot_compensation(gs,
+                        parent = "Single Cells")
> # Visualise compensated data
Warning messages:
1: In doTryCatch(return(expr), name, parentenv, handler) :
  display list redraw incomplete
2: In doTryCatch(return(expr), name, parentenv, handler) :
  invalid graphics state
3: In doTryCatch(return(expr), name, parentenv, handler) :
  invalid graphics state
> cyto_plot_compensation(gs,
+                        parent = "Single Cells",
+                        spillover = "Spillover-Matrix.csv",
+                        compensate = TRUE)
**Error in plot.new() : figure margins too large**
```
I don't understand why the error occurred or what I might do to avoid it.  Any insights?

**Comment by DillonHammill** [comment]
@rwbaer, this warning is just telling you that there is not enough space to construct all the plots. You can increase the plotting space by increasing the size of the plots pane in RStudio. Otherwise you can call `cyto_plot_new(popup = TRUE)` to open a new pop-up window. This window can then be maximized before calling `cyto_plot_compensation()`.

**Comment by rwbaer** [comment]
I thought I thanked you yesterday, but apparently I never hit comment.

As a follow-up, how do you personally manage the huge number of plot windows that can be/are created during manual cytometry processing.  Do you use RStudio notebooks?  Are they effective?  Is there a way to co-opt shinny like you did for the spillover editor so we could have a tabbed set of figures?  It seems you cannot detach the plot window like you can the source window in RStudio, and the R graphics device history is not the most robust plot manager.

I'd be grateful for any best practices you might offer here.

**Comment by DillonHammill** [comment]
@rwbaer, the plots can also be assigned to R objects and recalled later if that helps?

```{r}
# Save plot to p
p <- cyto_plot(gs,
               parent = "root",
               alias = "Cells",
               channels = c("FSC-A", "SSC-A"))
# Calling p will bring up plot
p
```

I think it is easy enough to save the images you want using `cyto_plot_save()`, I discard any other images.
