### ISSUE TITLE
Experimental Details Editor doesn't like row elimination

### ISSUE THREAD

**Issue by rwbaer** [DillonHammill/CytoExploreR#49]
**Briefly describe what you hope to achieve:**
Context: started with cyto_setup() procedure in preparation for a 2 channel spill correction scenario.

I was trying to use the experimental details editor to eliminate two files in a folder that were unnecessary for 2 channel spill correction.  The editor provides the opportunity to right click and delete row.  I did so.  However, it seems unhappy if you do so and produces an error when you click save.  See image below.

![DetailsEditor](https://user-images.githubusercontent.com/3155051/82576729-a1f2ff80-9b4f-11ea-9075-439c2475e46a.png)

**Outline the steps taken to attempt to reach this goal (paste code below):**
- Include all data preparation steps where appropriate.
```{r}
Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length
```

**Include any associated screenshots or images here:**

**Comment by DillonHammill** [comment]
@rwbaer, this operation is not supported and probably never will be. It is too easy to accidentally remove files this way.

Use `cyto_select()` to pull out a subset of files and then pass them to the spillover functions.

If you don't want the files at all, use the `exclude` argument in `cyto_setup()`.

**Comment by rwbaer** [comment]
- I completely missed the exclude argument to cyto_setup()  Sounds perfect.
- cyto_select() sounds like another reasonable approach that works.  Thanks for that solution too.

- As to the behavior of the _**Experimental Details editor**_ that we are automatically forced to interact with during cyto_setup(),  I do not understand its purpose if we can't/shouldn't edit anything.  Why does it support row delete and column delete choices in its context menu if they can only get us in trouble?  Why would we be wanting to edit the spelling of file names?  What other role(s) is this editor to be playing in the setup sequence?

I want to be sure you know ...
Please know that I am by nature a prolific provider of feedback, and that I very much appreciate the beautiful software you have created here.  Do not take my feedback as my disappointment with your efforts.  To the contrary, I'm VERY blown away by them and very grateful that you have accomplished what you have.   I'm also very grateful for your patience with me as I discover my way through putting your project into action.  Hopefully, I'll catch on soon.

**Comment by DillonHammill** [comment]
@rwbaer, if you don't want the editors to open set `markers = FALSE` and `details =FALSE` in `cyto_setup()`.

Column deletion is fine, but the name column should not be edited. I will put some restrictions on this so that this is more clear.

**Comment by rwbaer** [comment]
Ahhh....  '...more columns...'
This aspect of cyto_setup() likely will be much more interesting/important when I finally get beyond spillover and gate setup and begin analyzing unknown samples with potentially  more columns and fields that could need editing at setup time .  
I'm still walking (limping); not running but each insight helps.
