### ISSUE TITLE
Transform help

### ISSUE THREAD

**Issue by rwbaer** [DillonHammill/CytoExploreR#52]
**Briefly describe what you hope to achieve:**
Trying to preform a default transformation and get an error I can't decipher

**Outline the steps taken to attempt to reach this goal (paste code below):**
- Include all data preparation steps where appropriate.
```{r}
# Initialize a gating set
gs.unk <- cyto_setup("Samples",
                 gatingTemplate = "Analysis-gatingTemplate.csv",
                 details = TRUE)

cyto_gatingTemplate_select("Analysis-gatingTemplate") # make sure

# Apply compensation
gs.unk <- cyto_compensate(gs.unk,
                      spillover = "Spillover-Matrix.csv")

# Transform fluorescent channels - default logicle transformations
gs.unk <- cyto_transform(gs.unk) # Transforms and plots transformed plot
Error in .lgclTrans(x, p, ...) : w is negative!Try to increase 'm'
> 
```
When i look at the parameters for cyto_transform() I don't see anything with names like w or m and I can't figure out how to drill down to find the underlying functions I should be looking at.

**Include any associated screenshots or images here:**

**Comment by DillonHammill** [comment]
See comments on issue #51 about the `cyto_transformer()` functions. It is common to encounter this error with the logicle transformation and it can be difficult to fix. I would considering using a biexponential transformation in this case.
