### ISSUE TITLE
Parsing of underscore in Experiment Markers Editor

### ISSUE THREAD

**Issue by rwbaer** [DillonHammill/CytoExploreR#53]
**Briefly describe what you hope to achieve:**
Using the .fcs files from my S3 Flow sorter, I get default entries in the marker channel for time that duplicate because the underscore terminates parsing and the full channel name is not passed to the marker column.  This results in a duplicate label error.  Also, not sure about the resulting message, "Trying to assing the ..."  Is there a typo?

**Outline the steps taken to attempt to reach this goal (paste code below):**
- Include all data preparation steps where appropriate.
```{r}
> gs <- cyto_setup("Compensation-Samples",
+                  gatingTemplate = "Compensation-gatingTemplate.csv",
+                  restrict = TRUE,
+                  clean = FALSE,
+                  details = TRUE)
Loading FCS files into a GatingSet...
Assigning markers to channels...
Experiment-Markers.csv found in working directory.
Error in `markernames<-`(`*tmp*`, value = value) : 
  Trying to assing the marker: TIME- to multiple channels)
```

**Include any associated screenshots or images here:**
![image](https://user-images.githubusercontent.com/3155051/83265005-878bd800-a186-11ea-9c59-030e074a68ae.png)

**Comment by DillonHammill** [comment]
@rwbaer, that is a funny typo. Ut is supposed to say "Trying to assign the marker TIME- to multiple channels". Basically, the markers must be unique for each channel and `TIME-` is being assigned to the first two channels. Modify these to be unique in the editor and you should have no issues.

**Comment by rwbaer** [comment]
This is a "user-fixable" issue, as you point out, and so "will not fix" is possibly an appropriate response. However, I consider this a "workaround " for the reported problem which was the default assignment of Time- to the Marker column.  It was not me that provided that "Time-" value in two rows, but perhaps the default marker column values are generated outside your code.  There is a parser somewhere in the programming chain that stops parsing Time_LSW and Time_MSW at the underscore when there was no parameter value to fill in for the marker column.
