### ISSUE TITLE
clean argument in cyto_setup

### ISSUE THREAD

**Issue by rwbaer** [DillonHammill/CytoExploreR#59]
**Briefly describe what you hope to achieve:**
**Current issue**
I wish to set the clean argument to TRUE in cyto_setup.  When I do so it produces an error that I can't immediately interpret.  Not sure what "FileType no found" might mean.

**Future issue:**
The result of setting the 'clean' argument to TRUE seems to be to call flow_auto_qc() in the flowAI package.   Looking at the help for this function I see another potential problem just ahead (perhaps) and that is that flow_auto_qc has a timeCh argument that is by default set to NULL.  NULL indicates that the name of the time channel will be "retrieved automatically". The alternative is to supply the text name of the TIME channel.   I worry that this will not work for me since I have two time channels named TIME_LSW and TIME_MSW.  The way cyto_setup() works, I don't know how I would supply a proper text argument to timeCh to set one of those two channels to my time channel.

**Outline the steps taken to attempt to reach this goal (paste code below):**
```{r}
Show in New WindowClear OutputExpand/Collapse Output
Skipping install of 'CytoExploreR' from a github remote, the SHA1 (0f0fdb7b) has not changed since last install.
  Use `force = TRUE` to force installation
Show in New WindowClear OutputExpand/Collapse Output
Error in flow_auto_qc(x, html_report = FALSE, mini_report = FALSE, fcs_QC = FALSE, : object 'FileType' not found
Show in New WindowClear OutputExpand/Collapse Output
Error in `[<-.data.frame`(`*tmp*`, , "channel", value = c(Channel1 = "FL3-AREA", : replacement has 4 rows, data has 2
> gs <- cyto_setup("Compensation-Samples",
+                  gatingTemplate = "Compensation-gatingTemplate.csv",
+                  restrict = TRUE,
+                  clean = TRUE,
+                  details = TRUE)
Loading FCS files into a GatingSet...
Assigning markers to channels...
Experiment-Markers.csv found in working directory.
Updating experiment details...
Experiment-Details.csv found in working directory.
Removing unassigned channels...
Cleaning data to remove anomalies...
Error in flow_auto_qc(x, html_report = FALSE, mini_report = FALSE, fcs_QC = FALSE,  : 
  object 'FileType' not found
```

**Include any associated screenshots or images here:**

**Comment by DillonHammill** [comment]
@rwbaer, `cyto_setup()` is designed to simplify the process of loading and annotating samples without making too many compromises. If you need more control over the data cleaning process, you can load the samples in first and then manually apply `cyto_clean()` which will accept all of the arguments of `flow_auto_qc()`. For example:
```{r}
# Load & annotate & restrict samples
gs <- cyto_setup("Compensation-Samples",
                 gatingTemplate = "Compensation-gatingTemplate.csv",
                 restrict = TRUE,
                 details = TRUE)

# Use cyto_clean to remove anomalies
gs <- cyto_clean(gs,
                 timeCh = "TIME_LSW")
```
I have also been meaning to add support for controlling the types of anomaly checks to perform in `cyto_setup()` when `clean` is not FALSE. The reason for this is that the dynamic range checks often remove beads and this is obviously not desirable. I just pushed an update to `cyto_setup()` to allow user to pass the types of anomaly checks to perform through the `clean` argument. This argument now accepts anything expected by the `remove_from` argument in `flow_auto_qc()`, for example to perform only the flow rate (FR) check:
```{r}
gs <- cyto_setup("Samples",
                  clean = "FR")
```
I think the first code snippet above will address your issue, if you are still having the same problem I can take another look. Just out of interest, why are there multiple time channels in your FCS files?

**Comment by rwbaer** [comment]
> Just out of interest, why are there multiple time channels in your FCS files?
I have NO idea.  When we first go the instrument there were not.  They appeared with a service upgrade, but there is not (or I have not been able to find) a technically oriented service manual to explain such things.  There may be something related to the sort function, but this is no more than one of my musings.

Thanks for the help.  I'll try breaking it down in steps and let you know how it goes.

**Comment by rwbaer** [comment]
It seems like maybe something changed in the dependencies??

```{r}
> cyto_markers(gs_test)
     TIME_LSW      FL3-AREA      FL4-AREA 
       "TIME"    "FL3-PE-A" "FL4-PerCP-A" 
> gs_test <- cyto_clean(gs_test,
+                  timeCh = "TIME_LSW")
Error in flow_auto_qc(cyto_data, html_report = FALSE, mini_report = FALSE,  : 
  object 'FileType' not found
```

And the traceback:

```
> cyto_markers(gs_test)
     TIME_LSW      FL3-AREA      FL4-AREA 
       "TIME"    "FL3-PE-A" "FL4-PerCP-A" 
> gs_test <- cyto_clean(gs_test,
+                  timeCh = "TIME_LSW")
Error in flow_auto_qc(cyto_data, html_report = FALSE, mini_report = FALSE,  : 
  object 'FileType' not found
```

**Comment by DillonHammill** [comment]
@rwbaer, I think I found the bug in `flowAI` are you able to send through an fcs file will multiple TIME parameters so that I can fix this?

**Comment by rwbaer** [comment]
See if this link gets you access to c6-1.fcs: https://drive.google.com/open?id=14IvDzKTqGmDkKQ0_w88uyIfenXh9QO4n&authuser=rbaer%40atsu.edu&usp=drive_fs

**Comment by DillonHammill** [comment]
Thanks I have sent an access request.

**Comment by rwbaer** [comment]
I got the access request, but only hope I clicked the right things that you actually got access.  Let me know if I need to try again.

**Comment by DillonHammill** [comment]
@rwbaer, as you can see I have made the required changes to `flowAI` which should be available soon. In the meantime, you can try out the update to make sure it fixes the problem:
```{r}
devtools::install_github("DillonHammill/flowAI")
```

**Comment by DillonHammill** [comment]
@rwbaer, these changes have now been incorporated into `flowAI`. Please pull down the latest GitHub version to see if it resolves this issue for you:
```{r}
devtools::install_github("giannimonaco/flowAI")
```

**Comment by rwbaer** [comment]
@DillonHammill , Thanks.  I tried with your version on an 8 GB machine and ran into memory sufficiency problems.  Haven't had a chance to try on a machine with more memory.  I'll try to get to this soon with a more capable machine but my 32 GB machine and try is in Windows update hell for the moment.  May try on my MacBook, but I have to do some installing first.
