### ISSUE TITLE
New cyto_plot issue after install of CytoExploreR

### ISSUE THREAD

**Issue by Andyroo1966** [DillonHammill/CytoExploreR#6]
Since I installed CytoExploreR, the version of cyto_plot throw up this error when trying to plot.

eg:   cyto_plot(gs,parent="root", channels = c("FSC-A","SSC-A"))
Error in pd_split[[z]][, "name"] : incorrect number of dimensions

other plotting such as cyto_plot_gating_tree(gs) - work fine.
![image](https://user-images.githubusercontent.com/34082637/74808044-e985a780-5324-11ea-9240-ba4461f7fa54.png)

regards

Andrew Lucas
University of Western Australia

**Comment by DillonHammill** [comment]
Hmmm, can't say that I have seen this one. Please can you send through your gatingTemplate so that I can troubleshoot this. Thanks for reporting.

**Comment by Andyroo1966** [comment]
Hi again Dillon.

cyto_details(gs)
                                                     name
S1 H34CSL7_Heart Ntv_029.fcs S1 H34CSL7_Heart Ntv_029.fcs
S1 H34CSL7_Heart Tx_030.fcs   S1 H34CSL7_Heart Tx_030.fcs
S2 H31CSL7_Heart Ntv_035.fcs S2 H31CSL7_Heart Ntv_035.fcs
S2 H31CSL7_Heart Tx_036.fcs   S2 H31CSL7_Heart Tx_036.fcs
S3 H35CSL7_Heart Ntv_041.fcs S3 H35CSL7_Heart Ntv_041.fcs
S3 H35CSL7_Heart Tx_042.fcs   S3 H35CSL7_Heart Tx_042.fcs



[gating_panel_1.csv.zip](https://github.com/DillonHammill/CytoExploreR/files/4223905/gating_panel_1.csv.zip)

cyto_gate_draw works as expected....

**Comment by DillonHammill** [comment]
Thanks I will look into it and get a fix up ASAP.

**Comment by Andyroo1966** [comment]
I have an install on another machine at home.  Will take a look at that to see if consistent.  This is an R3.6 Mac Mojave install.  The other install I think is R3.6. Catalina.
regards

**Comment by DillonHammill** [comment]
This should now be fixed @Andyroo1966. Install the latest version and try again.
```{r}
devtools::install_github("DillonHammill/CytoExploreR")
```
Fortunately all the code refactoring has made it easy to locate and fix errors. Please let me know if the problem persists.

**Comment by Andyroo1966** [comment]
All fixed.  Interestingly, plotting was working ok on the other install...  I have updated both installs and both plotting fine now.  Thanks
