### ISSUE TITLE
Exporting statistics of samples selected by experiment variables 

### ISSUE THREAD

**Issue by Mieszkol** [DillonHammill/CytoExploreR#62]
Hi Dillon, 

Did you consider adding a possibility of selecting samples to export statistics by using experiment variables? The same way you can do it for gating? To be precise, using` select = `argument in `cyto_stats_compute()` as in `cyto_gate_draw()`. E.g.:

```
cyto_stats_compute(gs, parent = "T cells", alias = "CD4+", stat = "count", select = list(treatment = c("IL2")))

cyto_gate_draw(gs, parent = "T cells", alias = CD4+", channels = c("CD4", "CD8"), type = "rectangle", select = list(treatment = c("IL2")))

```

Best
Mieszko

**Comment by DillonHammill** [comment]
I  can certainly do that! I will try and add this tomorrow. Thanks for the suggestion, surprised I haven't already done that!

**Comment by DillonHammill** [comment]
@Mieszkol, I just pushed changes to add a `select` argument to `cyto_stats_compute()`. Please pull down the latest CytoExploreR:
```{r}
devtools::install_github("DillonHammill/CytoExploreR")
```

**Comment by Mieszkol** [comment]
@DillonHammill Thank you for such a quick reaction! It works very well.

**Comment by DillonHammill** [comment]
@Mieszkol, just pointing out that I added a select argument to `cyto_plot()` as well if you would like to try it out. For example if you only wanted to plot samples treated with Stim-D:
```{r}
cyto_plot(gs,
          parent = "CD4 T Cells",
          channels = c("CD44", "CD69"),
          select = list(Treatment = "Stim-D"))
```

**Comment by Mieszkol** [comment]
@DillonHammill Great! Thanks for letting me know.
