### ISSUE TITLE
Plotting 1d gate in 2d scatter plot

### ISSUE THREAD

**Issue by jonasmac16** [DillonHammill/CytoExploreR#65]
If one creates a 1d gate by using for example mindensity in the SSC-A dimension and then wants to plot the gate in a 2d plot(FSC-A v SSC-A), the gate is plotted in the first dimension(FSC-A) instead of the correct second dimension(SSC-A)

I could not create MWE quickly but I hope these two commands with the resulting plots illustrate the issue:

This plots the incorrect gate in the FSC-A dimension for "lymphocytes" which was actually gated in SSC-A
> cyto_plot(indv_gatingset_list_CD4_CD8[[1]][7], parent="boundary", channels=c("FSC-A","SSC-A"), alias=c("lymphocytes"), group_by="patient", display=0.7, contour_lines=0, label_text="lymphocytes")

![Rplot_incorrect](https://user-images.githubusercontent.com/25138850/86140142-75d08400-bae8-11ea-82f3-11cc04da996d.png)

This plots the correct gate in the SSC-A dimension for "lymphocytes"
> cyto_plot(indv_gatingset_list_CD4_CD8[[1]][7], parent="boundary", channels=c("SSC-A","FSC-A"), alias=c("lymphocytes"), group_by="patient", display=0.7, contour_lines=0, label_text="lymphocytes")

![Rplot_correct](https://user-images.githubusercontent.com/25138850/86140210-8b45ae00-bae8-11ea-92b7-9f893391e6a9.png)

While the second plot is correct it is not ideal since we commenly plot FSC-A v SSC-A and not the other way around

 - OS: Linux

**Comment by DillonHammill** [comment]
Thanks for reporting this @jonasmac16, there was in fact a bug in the gate conversion code. I just pushed the update, please pull down the latest CytoExploreR (no need to update RGLab packages):
```{r}
devtools::install_github("DillonHammill/CytoExploreR")
```
