### ISSUE TITLE
cyto_gate_draw() erases parent gate information in gatingTemplate.csv

### ISSUE THREAD

**Issue by northNomad** [DillonHammill/CytoExploreR#67]
Hi,

Created a GatingTemplate and gated for >lymph >marker1

```
> cyto_gate_draw(gs,
+                channels = c("FSC.A", "SSC.A"),
+                parent = "root",
+                alias = "lymph",
+                gatingTemplate = "./gatingTemplate.csv",
+                ylim = c(0, 1e6)
+                )
Select at least 3 points to construct a polygon gate around the lymph population. 

Creating ./hsa_ccl_clec5a_profile.csv to save the constructed gate(s).
Adding newly constructed gate(s) to ./hsa_ccl_clec5a_profile.csv .
...
done
```

```
> cyto_gate_draw(gs,
+                channels = c("FSC.A", "FL4.H"),
+                parent = "lymph",
+                alias = "marker1",
+                gatingTemplate = "./gatingTemplate.csv",
+                select = list(ccl = c("oci2", "U937")),
+                type = "rectangle"
+                )
Select 2 diagonal points to construct a rectangle gate around the mdl1+ population. 
```

Now I erase environment and rerun my script with ```cyto_gatingTemplate_apply()```

```
> cyto_gatingTemplate_apply(gs, "gatingTemplate.csv")
Applying gatingTemplate.csv to the GatingSet...
Error in .getFullPath(this_row[, parent], new_dt) : 
  Not able to to find reference to: lymph
```

Best,
NN

**Comment by DillonHammill** [comment]
@northNomad, if you read the meesages in the first code it looks like the gates are being saved somewhere else - `./hsa_ccl_clec5a_profile.csv` and not to `gatingTemplate.csv`. I would remove the `./` in front of `gatingTemplate.csv` and it should work fine. I would also check the output of `cyto_gatingTemplate_active()` to see which gatingTemplate you are using.

**Comment by DillonHammill** [comment]
The reason why this is happening is because of the internal working directory check, which was added a long time ago to prevent users from attempting to use gatingTemplates outside their current working directory. These checks have all been removed in upcoming version of CytoExploreR so this should no longer be an issue. In the meantime, if you want to turn off these working directory checks run `options(CytoExplorerR_wd_check = FALSE)` at the top of your scripts.

**Comment by northNomad** [comment]
> @northNomad, if you read the messages in the first code chunk it looks like the gates are being saved somewhere else - `./hsa_ccl_clec5a_profile.csv` and not to `gatingTemplate.csv`. I would remove the `./` in front of `gatingTemplate.csv` and it should work fine. I would also check the output of `cyto_gatingTemplate_active()` to see which gatingTemplate you are using.

Removing the ```.``` before the slash solved the problem

Spot on!
Thanks so much as always!
