### ISSUE TITLE
Unable to extract spillover matrix from selected sample

### ISSUE THREAD

**Issue by Mieszkol** [DillonHammill/CytoExploreR#75]
Hi Dillon, 
I'm using a different mac than I usually do and when analyzing the same FCS files I did before I encountered a compensation error

```
> gs <- cyto_compensate(gs)
Error in cyto_compensate.GatingSet(gs) : 
  Unable to extract spillover matrix from selected sample.
> cyto_spillover_extract(gs)
NULL
> spill <- cyto_spillover_edit(gs, parent = "Single Cells Comp", spillover = paste(Full.Exp.Name, "CompMatrix.csv", sep = ""))
Error in `colnames<-`(`*tmp*`, value = channels) : 
  attempt to set 'colnames' on an object with less than two dimensions
```

I uninstalled R, removed all the libraries, and reinstalled CytoExploreR with all the dependencies but the problem persists. The spillover matrix is definitely attached to these FCS files - I've used the exact same ones before on the other mac (which may have an older version of CytoExploreR installed). Could you help me with that? Thanks!

Best
Mieszko

**Comment by DillonHammill** [comment]
@Mieszkol, thanks for reporting this. This is due to recent changes in the RGLab suite of packages - the old DESCRIPTION extraction method is now depreciated. I will need to switch over to using `keyword()` within `cyto_spillover_extract()` to fix this. Working on this now.

**Comment by DillonHammill** [comment]
@Mieszkol this should now be fixed. Please pull down the latest CytoExploreR and let me know how you go:
```{r}
devtools::install_github("DillonHammill/CytoExploreR")
```

I think this is the only place where this change needs to be made, but I will check just be sure.

**Comment by Mieszkol** [comment]
@DillonHammill I did a quick test and it seems that it works now. Thanks!
