### ISSUE TITLE
Assigning colours to samples in cyto_gate_draw()

### ISSUE THREAD

**Issue by Mieszkol** [DillonHammill/CytoExploreR#77]
Hi Dillon, 
I encountered a problem - when I used my FMO-1 controls for gating, the range of the axis in cyto_gate_draw() was so small I couldn't set the gate far enough to cover all of the positive population in regular samples. Then, I thought a great solution would be if I could use both, FMO-1 control and a regular sample for gating and distinguish them by colours. I tried doing that with 
 
`cyto_gate_draw(gs, parent = "NK", alias = "CX3CR1", channels = c("CX3CR1", "CD56"), type = "rectangle", select = list(control = c("FMO-CR", "4C")), point_col = c("red", "blue"))`

but it didn't work as expected. I think a really usefull feature would be if one could choose colour for each sample in cyto_gate_draw(), but also have an option to leave the default density-dependent colour scale. For example, in this case, I'd like to be able to leave the default, density-dependent colour scale for my FMO-CR sample while assigning e.g. dark grey color to 4C sample. Would you consider adding such feature?

**Comment by DillonHammill** [comment]
@Mieszkol this is already supported, you just need to modify your code a bit. Remember that `cyto_gate_draw()` calls `cyto_plot()` internally so the plotting behaves exactly the same and you can pass `cyto_plot()` arguments to `cyto_gate_draw()` as well.

**axes ranges**
If your events are not being displayed or you need more space to draw your gates, you can change the `axes_limits`, `xlim` and `ylim` arguments. For example, setting `axes_limits = "machine"` will display the entire axes ranges and give more space for gating (this is the default). Alternatively you can use `xlim` and `ylim` to have more fine control over the axes ranges - these arguments are basically used for zooming in and out. Just remember that `cyto_plot()` will automatically down-sample to 25000 events by default, so if you are dealing will rarer populations you may need to increase this limit to make the events visible on the plot.

**overlays**
The `select` argument as used in your snippet pulls out the relevant samples and merges them, then displays these as the base layer in the plot with density colour scale. If you want these to be coloured differently you need to pass the FMO through the `overlay` argument. For example:
```{r}
# extract FMO
FMO <- cyto_extract(gs,
                    parent = "NK",
                    select = list(control = "FMO"))

# overlay FMO during gating
cyto_gate_draw(gs, 
               parent = "NK",
               alias = "CX3CR1", 
               channels = c("CX3CR1", "CD56"), 
               type = "rectangle",
               select = list(control = c("4C")), 
               overlay = FMO,
               point_col = c("red", "blue"))
```

**Comment by Mieszkol** [comment]
@DillonHammill Thank you for this great explanation, it's works perfectly!
