### ISSUE TITLE
Integration with SingleCellExperiment object?

### ISSUE THREAD

**Issue by MikhaelManurung** [DillonHammill/CytoExploreR#8]
Hi Dillon,

What an amazing effort! Thanks for your contribution to the open-source community. 

Is there any plan to provide an integration to SingleCellExperiment object? I use it a lot for CyTOF data analysis. I would find it amazing if I could do a simple biaxial gating on my cell clusters and then somehow have the information (e.g. marker positivity) back to my SCE object again.

Best,
Mikhael

**Comment by DillonHammill** [comment]
Hi @MikhaelManurung,

What are the benefits of working with SCE objects? Are there any particular features that you like/need?

Dillon

**Comment by Biomiha** [comment]
Hi Dillon,

I also use SCE objects for CyTOF data. The benefits are that it holds both assay (i.e. in this case exprs but can hold others) information along with reduced dim information in one object. It supports matrices, data.frames and delayed arrays as input. Subsetting of cells also subsets the reducedDims slots, etc.  I can see a scenario where a single SCE object holds the raw data, the transformed data (with the metadata slot holding information on the type of transformation), the reducedDims, experiment info and probably gate information as well. Maybe for the future but the package is already amazing.

Best wishes,
Miha

**Comment by MikhaelManurung** [comment]
Sorry for the late reply @DillonHammill. @Biomiha explains the advantages of SCE object quite well. And I concur that this package (I finally managed to install it!!) is great at what it is trying to do. I can just export gated populations into separate fcs files when I want to do things in packages that accept SCE object as input. 

Best wishes,
Mikhael
