### ISSUE TITLE
Enabling option for grid in the plot background

### ISSUE THREAD

**Issue by siveenks** [DillonHammill/CytoExploreR#83]
Hi,
I have to perform lot of manual gating using CytoExploreR package and one of the drawbacks I found was the absence of a grid in the background of the plot. 
![image](https://user-images.githubusercontent.com/66004024/90963292-1034be80-e4bf-11ea-8614-b1aa4a379250.png)

When plotting with ggplot, we can get a grid in the background (example attached). 

![image](https://user-images.githubusercontent.com/66004024/90963088-b97ab500-e4bd-11ea-8e00-e4e1b80b6ea8.png)

This help to decide the spot to click to generate a quadrant which will split the plot with a nice separation, or when creating a rectangle gates, help me to decide on which spots to click for generating the gate.

It would be really helpful if the cyto_plot_theme function has options for a background grid. 

Thank you in advance.

Regards,
Siveen

**Comment by DillonHammill** [comment]
Thanks again for the suggestion @siveenks! I have added support for grid lines in version 2.0.0 of CytoExploreR (coming soon).

In fact, I like them so much that they are now turned on by default! Check out the the `grid_` arguments for more details. I also added support for quantile lines by passing the probabilities directly through the grid argument (e.g. `grid = c(0.05, 0.95)`).

The new version will be out very soon, here is a sneak peak at the new plots:
![image](https://user-images.githubusercontent.com/28646736/137042279-fa8aaa29-c768-4d24-95dc-dda2e0b3f2c3.png)
