### ISSUE TITLE
Installation issues of the dependencies

### ISSUE THREAD

**Issue by hally166** [DillonHammill/CytoExploreR#9]
Hi Dillon,
The tool looks great.
Is there a chance you could expand on how to install CytoExploreR?  Specifically how to install the GitHub repo dependencies.  I've been battling with them for the past two days without success.  
I have managed to install RProtoBufLib and cytolib, but I am now stuck on flowCore.  You can see my issues on their issue trackers.  I presume my main issues arrise because the GitHub repos are fluid and constantly changing.  I can see from the screenshots (and the same issue you had with RProtoBfLib) that you also use windows :) 
Thanks
Chris

**Comment by hally166** [comment]
As suggested on the flowCore issues page I a trying the devel version of bioconductor which should install the correct versions...

**Comment by gringer** [comment]
We're also having trouble installing CytoExploreR dependencies on our computers. Running `install_github("RGLab/RProtoBufLib", ref = "trunk")` on a Mac system produced an error saying that it could not open the URL. R is looking for this location:

https://api.github.com/repos/RGLab/RProtoBufLib/tarball/trunk

**Comment by DillonHammill** [comment]
@gringer I believe the "trunk" branch has been deleted from RProtoBufLib. Try installing from the `master` branch:
`install_github("RGLab/RProtoBufLib")`

**Comment by DillonHammill** [comment]
The same goes for `flowStats`, all of the RGLab packages are now using `master` as their default branch - which is a welcomed change.
`install_github("RGLab/flowStats")`

I will update the website accordingly.

**Comment by NDasyam** [comment]
Hi there @gringer asked be to paste the error message we encountered here it is :

=== configuring in third_party/googletest (/private/var/folders/d9/_2f181rd5kddy7wmdr1yz7sc000107/T/RtmpTiL6Qa/R.INSTALL608d537fa2ce/RProtoBufLib/src/protobuf-3.10.0/third_party/googletest)
configure: WARNING: no configuration information is in third_party/googletest
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /private/var/folders/d9/_2f181rd5kddy7wmdr1yz7sc000107/T/RtmpTiL6Qa/R.INSTALL608d537fa2ce/RProtoBufLib/src/protobuf-3.10.0/missing autoconf
/private/var/folders/d9/_2f181rd5kddy7wmdr1yz7sc000107/T/RtmpTiL6Qa/R.INSTALL608d537fa2ce/RProtoBufLib/src/protobuf-3.10.0/missing: line 81: autoconf: command not found
WARNING: 'autoconf' is missing on your system.
         You should only need it if you modified 'configure.ac',
         or m4 files included by it.
         The 'autoconf' program is part of the GNU Autoconf package:
         <https://www.gnu.org/software/autoconf/>
         It also requires GNU m4 and Perl in order to run:
         <https://www.gnu.org/software/m4/>
         <https://www.perl.org/>
make: *** [configure] Error 127
configure: creating ./config.status
config.status: creating src/Makevars
** libs
mkdir -p "/Users/ndasyam/Library/R/3.6/library/00LOCK-RProtoBufLib/00new/RProtoBufLib/include"
cp -r /private/var/folders/d9/_2f181rd5kddy7wmdr1yz7sc000107/T/RtmpTiL6Qa/R.INSTALL608d537fa2ce/RProtoBufLib/src/pb_build/include/google /Users/ndasyam/Library/R/3.6/library/00LOCK-RProtoBufLib/00new/RProtoBufLib/include
cp: /private/var/folders/d9/_2f181rd5kddy7wmdr1yz7sc000107/T/RtmpTiL6Qa/R.INSTALL608d537fa2ce/RProtoBufLib/src/pb_build/include/google: No such file or directory
make: *** [copying] Error 1
ERROR: compilation failed for package ‘RProtoBufLib’
* removing ‘/Users/ndasyam/Library/R/3.6/library/RProtoBufLib’
* restoring previous ‘/Users/ndasyam/Library/R/3.6/library/RProtoBufLib’
Error: Failed to install 'RProtoBufLib' from GitHub:
  (converted from warning) installation of package ‘/var/folders/d9/_2f181rd5kddy7wmdr1yz7sc000107/T//Rtmp76ZKGW/file600355c99c8c/RProtoBufLib_1.9.7.tar.gz’ had non-zero exit status

**Comment by DillonHammill** [comment]
Looks like you will need to install GNU G4, perl and autoconf on your system.
https://www.gnu.org/software/m4/
https://www.perl.org/
https://www.gnu.org/software/autoconf/

**Comment by DillonHammill** [comment]
@NDasyam did you set the LIB_PROTOBUF environment variable correctly?

![image](https://user-images.githubusercontent.com/28646736/75953112-b9cdc680-5f04-11ea-925f-d1249b5153ba.png)

Make sure that you use forward slashes and not back slashes. May as well check that your LIB_XML2 environment variable is also correctly set.

Also double check that protobuf exists in C: and that the folder contains an include and lib folder.
![image](https://user-images.githubusercontent.com/28646736/75953346-4bd5cf00-5f05-11ea-9c51-4c7d93e71662.png)

**Comment by hally166** [comment]
Using R 4.0 and biocManager 3.11 (the development versions) didn't work because flowWorkspace doesn't install in R4.0.  This is probably because the current version of RTools 4.0b22 has a bug in it leading it not to be recognised [https://github.com/r-lib/devtools/issues/2148](url)
I failed completely with using R3.6.3 as flowCore would not install form GitHub.
Hopefully with the final releases of R 4.0 and biocManager 3.11 these issues will be resolved.

**Comment by DillonHammill** [comment]
@hally166 I would try the release version of R. I think your issue with flowCore was to do with your incorrect protobuf setup.

**Comment by hally166** [comment]
Sadly not, it is still failing on installing flowCore@master from GitHub
```
> install_github("RGLab/flowCore")
Downloading GitHub repo RGLab/flowCore@master
√  checking for file 'C:\Users\chall\AppData\Local\Temp\RtmpYdd6WN\remotes3d883e0e2bc2\RGLab-flowCore-486cc2c/DESCRIPTION' ...
-  preparing 'flowCore': (427ms)
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts (400ms)
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
     NB: this package now depends on R (>= 3.5.0)
     WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects: 'flowCore/data/GvHD.rda'  'flowCore/tests/testthat/expectResults.rds'
-  building 'flowCore_1.53.11.tar.gz'
   
* installing *source* package 'flowCore' ...
** using staged installation
** libs

*** arch - i386
C:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-3.6.3/include" -DNDEBUG  -I"C:/Program Files/R/R-3.6.3/library/Rcpp/include" -I"C:/Program Files/R/R-3.6.3/library/RcppArmadillo/include" -I"C:/Program Files/R/R-3.6.3/library/BH/include" -I"C:/Program Files/R/R-3.6.3/library/cytolib/include" -I"C:/Program Files/R/R-3.6.3/library/RProtoBufLib/include"        -O2 -Wall  -mtune=core2 -c FastLogicle.cpp -o FastLogicle.o
C:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-3.6.3/include" -DNDEBUG  -I"C:/Program Files/R/R-3.6.3/library/Rcpp/include" -I"C:/Program Files/R/R-3.6.3/library/RcppArmadillo/include" -I"C:/Program Files/R/R-3.6.3/library/BH/include" -I"C:/Program Files/R/R-3.6.3/library/cytolib/include" -I"C:/Program Files/R/R-3.6.3/library/RProtoBufLib/include"        -O2 -Wall  -mtune=core2 -c Hyperlog.cpp -o Hyperlog.o
C:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-3.6.3/include" -DNDEBUG  -I"C:/Program Files/R/R-3.6.3/library/Rcpp/include" -I"C:/Program Files/R/R-3.6.3/library/RcppArmadillo/include" -I"C:/Program Files/R/R-3.6.3/library/BH/include" -I"C:/Program Files/R/R-3.6.3/library/cytolib/include" -I"C:/Program Files/R/R-3.6.3/library/RProtoBufLib/include"        -O2 -Wall  -mtune=core2 -c Logicle.cpp -o Logicle.o
C:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-3.6.3/include" -DNDEBUG  -I"C:/Program Files/R/R-3.6.3/library/Rcpp/include" -I"C:/Program Files/R/R-3.6.3/library/RcppArmadillo/include" -I"C:/Program Files/R/R-3.6.3/library/BH/include" -I"C:/Program Files/R/R-3.6.3/library/cytolib/include" -I"C:/Program Files/R/R-3.6.3/library/RProtoBufLib/include"        -O2 -Wall  -mtune=core2 -c RcppExports.cpp -o RcppExports.o
C:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-3.6.3/include" -DNDEBUG  -I"C:/Program Files/R/R-3.6.3/library/Rcpp/include" -I"C:/Program Files/R/R-3.6.3/library/RcppArmadillo/include" -I"C:/Program Files/R/R-3.6.3/library/BH/include" -I"C:/Program Files/R/R-3.6.3/library/cytolib/include" -I"C:/Program Files/R/R-3.6.3/library/RProtoBufLib/include"        -O2 -Wall  -mtune=core2 -c biexponential.cpp -o biexponential.o
C:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-3.6.3/include" -DNDEBUG  -I"C:/Program Files/R/R-3.6.3/library/Rcpp/include" -I"C:/Program Files/R/R-3.6.3/library/RcppArmadillo/include" -I"C:/Program Files/R/R-3.6.3/library/BH/include" -I"C:/Program Files/R/R-3.6.3/library/cytolib/include" -I"C:/Program Files/R/R-3.6.3/library/RProtoBufLib/include"        -O2 -Wall  -mtune=core2 -c convertRawBytes.cpp -o convertRawBytes.o
C:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-3.6.3/include" -DNDEBUG  -I"C:/Program Files/R/R-3.6.3/library/Rcpp/include" -I"C:/Program Files/R/R-3.6.3/library/RcppArmadillo/include" -I"C:/Program Files/R/R-3.6.3/library/BH/include" -I"C:/Program Files/R/R-3.6.3/library/cytolib/include" -I"C:/Program Files/R/R-3.6.3/library/RProtoBufLib/include"        -O2 -Wall  -mtune=core2 -c fcsTextParse.cpp -o fcsTextParse.o
C:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-3.6.3/include" -DNDEBUG  -I"C:/Program Files/R/R-3.6.3/library/Rcpp/include" -I"C:/Program Files/R/R-3.6.3/library/RcppArmadillo/include" -I"C:/Program Files/R/R-3.6.3/library/BH/include" -I"C:/Program Files/R/R-3.6.3/library/cytolib/include" -I"C:/Program Files/R/R-3.6.3/library/RProtoBufLib/include"        -O2 -Wall  -mtune=core2 -c hyperlogTransform.cpp -o hyperlogTransform.o
C:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-3.6.3/include" -DNDEBUG  -I"C:/Program Files/R/R-3.6.3/library/Rcpp/include" -I"C:/Program Files/R/R-3.6.3/library/RcppArmadillo/include" -I"C:/Program Files/R/R-3.6.3/library/BH/include" -I"C:/Program Files/R/R-3.6.3/library/cytolib/include" -I"C:/Program Files/R/R-3.6.3/library/RProtoBufLib/include"        -O2 -Wall  -mtune=core2 -c inPolygon.cpp -o inPolygon.o
C:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-3.6.3/include" -DNDEBUG  -I"C:/Program Files/R/R-3.6.3/library/Rcpp/include" -I"C:/Program Files/R/R-3.6.3/library/RcppArmadillo/include" -I"C:/Program Files/R/R-3.6.3/library/BH/include" -I"C:/Program Files/R/R-3.6.3/library/cytolib/include" -I"C:/Program Files/R/R-3.6.3/library/RProtoBufLib/include"        -O2 -Wall  -mtune=core2 -c inPolytope.cpp -o inPolytope.o
C:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-3.6.3/include" -DNDEBUG  -I"C:/Program Files/R/R-3.6.3/library/Rcpp/include" -I"C:/Program Files/R/R-3.6.3/library/RcppArmadillo/include" -I"C:/Program Files/R/R-3.6.3/library/BH/include" -I"C:/Program Files/R/R-3.6.3/library/cytolib/include" -I"C:/Program Files/R/R-3.6.3/library/RProtoBufLib/include"        -O2 -Wall  -mtune=core2 -c logicleTransform.cpp -o logicleTransform.o
C:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-3.6.3/include" -DNDEBUG  -I"C:/Program Files/R/R-3.6.3/library/Rcpp/include" -I"C:/Program Files/R/R-3.6.3/library/RcppArmadillo/include" -I"C:/Program Files/R/R-3.6.3/library/BH/include" -I"C:/Program Files/R/R-3.6.3/library/cytolib/include" -I"C:/Program Files/R/R-3.6.3/library/RProtoBufLib/include"        -O2 -Wall  -mtune=core2 -c pairVectorRcppWrap.cpp -o pairVectorRcppWrap.o
C:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-3.6.3/include" -DNDEBUG  -I"C:/Program Files/R/R-3.6.3/library/Rcpp/include" -I"C:/Program Files/R/R-3.6.3/library/RcppArmadillo/include" -I"C:/Program Files/R/R-3.6.3/library/BH/include" -I"C:/Program Files/R/R-3.6.3/library/cytolib/include" -I"C:/Program Files/R/R-3.6.3/library/RProtoBufLib/include"        -O2 -Wall  -mtune=core2 -c poly_centroid.cpp -o poly_centroid.o
C:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-3.6.3/include" -DNDEBUG  -I"C:/Program Files/R/R-3.6.3/library/Rcpp/include" -I"C:/Program Files/R/R-3.6.3/library/RcppArmadillo/include" -I"C:/Program Files/R/R-3.6.3/library/BH/include" -I"C:/Program Files/R/R-3.6.3/library/cytolib/include" -I"C:/Program Files/R/R-3.6.3/library/RProtoBufLib/include"        -O2 -Wall  -mtune=core2 -c sortBytes.cpp -o sortBytes.o
C:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-3.6.3/include" -DNDEBUG  -I"C:/Program Files/R/R-3.6.3/library/Rcpp/include" -I"C:/Program Files/R/R-3.6.3/library/RcppArmadillo/include" -I"C:/Program Files/R/R-3.6.3/library/BH/include" -I"C:/Program Files/R/R-3.6.3/library/cytolib/include" -I"C:/Program Files/R/R-3.6.3/library/RProtoBufLib/include"        -O2 -Wall  -mtune=core2 -c uint2double.cpp -o uint2double.o
C:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-3.6.3/include" -DNDEBUG  -I"C:/Program Files/R/R-3.6.3/library/Rcpp/include" -I"C:/Program Files/R/R-3.6.3/library/RcppArmadillo/include" -I"C:/Program Files/R/R-3.6.3/library/BH/include" -I"C:/Program Files/R/R-3.6.3/library/cytolib/include" -I"C:/Program Files/R/R-3.6.3/library/RProtoBufLib/include"        -O2 -Wall  -mtune=core2 -c zeroin.cpp -o zeroin.o
C:/Rtools/mingw_32/bin/g++ -shared -s -static-libgcc -o flowCore.dll tmp.def FastLogicle.o Hyperlog.o Logicle.o RcppExports.o biexponential.o convertRawBytes.o fcsTextParse.o hyperlogTransform.o inPolygon.o inPolytope.o logicleTransform.o pairVectorRcppWrap.o poly_centroid.o sortBytes.o uint2double.o zeroin.o C:/PROGRA~1/R/R-3.6.3/library/cytolib/lib/i386/libcytolib.a -LC:/PROGRA~1/R/R-3.6.3/bin/i386 -lR
C:/PROGRA~1/R/R-3.6.3/library/cytolib/lib/i386/libcytolib.a(compensation.o):compensation.cpp:(.text+0x26): undefined reference to `google::protobuf::internal::fixed_address_empty_string'
C:/PROGRA~1/R/R-3.6.3/library/cytolib/lib/i386/libcytolib.a(compensation.o):compensation.cpp:(.text+0x47): undefined reference to `google::protobuf::internal::fixed_address_empty_string'
C:/PROGRA~1/R/R-3.6.3/library/cytolib/lib/i386/libcytolib.a(compensation.o):compensation.cpp:(.text+0x68): undefined reference to `google::protobuf::internal::fixed_address_empty_string'
C:/PROGRA~1/R/R-3.6.3/library/cytolib/lib/i386/libcytolib.a(compensation.o):compensation.cpp:(.text+0x89): undefined reference to `google::protobuf::internal::fixed_address_empty_string'
C:/PROGRA~1/R/R-3.6.3/library/cytolib/lib/i386/libcytolib.a(compensation.o):compensation.cpp:(.text+0xaa): undefined reference to `google::protobuf::internal::fixed_address_empty_string'
C:/PROGRA~1/R/R-3.6.3/library/cytolib/lib/i386/libcytolib.a(compensation.o):compensation.cpp:(.text+0x107): undefined reference to `google::protobuf::RepeatedPtrField<std::string>::Add()'
C:/PROGRA~1/R/R-3.6.3/library/cytolib/lib/i386/libcytolib.a(compensation.o):compensation.cpp:(.text+0x13f): undefined reference to `google::protobuf::RepeatedField<float>::Reserve(int)'
C:/PROGRA~1/R/R-3.6.3/library/cytolib/lib/i386/libcytolib.a(compensation.o):compensation.cpp:(.text+0x52e): undefined reference to `google::protobuf::RepeatedPtrField<std::string>::size() const'
C:/PROGRA~1/R/R-3.6.3/library/cytolib/lib/i386/libcytolib.a(compensation.o):compensation.cpp:(.text+0x53c): undefined reference to `google::protobuf::RepeatedPtrField<std::string>::Get(int) const'
collect2.exe: error: ld returned 1 exit status
if [ `uname -s` = 'Darwin' ]; then install_name_tool -change /usr/local/clang4/lib/libc++.1.dylib /usr/lib/libc++.1.dylib flowCore.dll; fi
no DLL was created
ERROR: compilation failed for package 'flowCore'
* removing 'C:/Program Files/R/R-3.6.3/library/flowCore'
* restoring previous 'C:/Program Files/R/R-3.6.3/library/flowCore'
Error: Failed to install 'flowCore' from GitHub:
  (converted from warning) installation of package ‘C:/Users/chall/AppData/Local/Temp/RtmpYdd6WN/file3d8852c37d9e/flowCore_1.53.11.tar.gz’ had non-zero exit status
```
cytolib 1.9.17
RProtoBufLib 1.9.7

**Comment by DillonHammill** [comment]
Hmmm... Did you install from BioC first then GitHub?

**Comment by hally166** [comment]
Yes.  I just tried `install_github("RGLab/flowCore", dependencies = TRUE)` just in case, but still with the same error.

**Comment by DillonHammill** [comment]
Did you try uninstalling and reinstalling everything as @mikejiang suggested?

**Comment by hally166** [comment]
Several times, including deleting all the packages.  Also tried having 4.0 and 3.6.2 installed one at a time.  This current one is a fresh install from 2 hours ago.
flowCore 1.53.11 installs from bioconductor 3.11, just not from GitHub, but then only in R 4.0, where flowWorkspace won't compile 😭

**Comment by mikejiang** [comment]
Again, github version is meant for linux users to build from source. For windows/mac users, there is prebuilt binaries available from bioc devel, which serves the very purpose in your case. It is typically only one-day behind the github (due to the delay of bioc nightly build cycle)

**Comment by DillonHammill** [comment]
@mikejiang, should I recommend that users install R4.0 and install the BioC devel packages for now? Do we still need to setup libxml2 and protobuf to get packages to build from here?

**Comment by mikejiang** [comment]
Installing binary from bioc does not require libxml2 and protobuf

**Comment by DillonHammill** [comment]
Ok and do we need clang and gfortran for mac?

**Comment by mikejiang** [comment]
Again, if installed from bioc as binary, no compiler is required

**Comment by DillonHammill** [comment]
Ok great! Thank you I will update the install instructions to use R4.0 and BioC-devel so that you don't get bombarded with installation issues. Thanks for your help!

**Comment by NDasyam** [comment]
@DillonHammill 

Sorry for the delay in replying , I had to work with our IT team who have the admin rights and I installed what you suggested and got all the dependencies loaded for our Mac systems

I used the following to get them all installed , after using the three links you had suggested I use

BiocManager::install("cytolib")
BiocManager::install("flowCore")
BiocManager::install("flowWorkspace")
BiocManager::install("flowStats")
BiocManager::install("openCyto")

I am at the last stage of running 
devtools::install_github("DillonHammill/CytoExploreR")

but it fails  with 

Installing package into ‘/Users/ndasyam/Library/R/3.6/library’
(as ‘lib’ is unspecified)
* installing *source* package ‘CytoExploreR’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Error: package ‘flowCore’ 1.52.1 was found, but >= 1.53.8 is required by ‘CytoExploreR’
Execution halted
ERROR: lazy loading failed for package ‘CytoExploreR’
* removing ‘/Users/ndasyam/Library/R/3.6/library/CytoExploreR’
Error: Failed to install 'CytoExploreR' from GitHub:
  (converted from warning) installation of package ‘/var/folders/d9/_2f181rd5kddy7wmdr1yz7sc000107/T//RtmpiNLMjw/file19d1685961c/CytoExploreR_1.0.2.tar.gz’ had non-zero exit status

**Comment by DillonHammill** [comment]
I am working on it now. You will need the development versions of these packages but the GitHub versions are not compiling. I will let you know once I have ironed out the install instructions.

**Comment by NDasyam** [comment]
Thank you and thanks for your earlier advice as well!!

**Comment by hally166** [comment]
Hi Dillon,
I am getting very very close after following your instructions in #12 

However (1), I think using the binary option only installs the binary and not the dependecies, so I had to drop that option.
However (2), flowWorkspace will only install from source, and only after individually updating "matrixStats", "glue", and restarting R, but these are probably random locked packages on my R installation. 
Now however(3) CytoExploreR won't install from GitHub with the following error:
```
> devtools::install_github("DillonHammill/CytoExploreR")
Downloading GitHub repo DillonHammill/CytoExploreR@master
√  checking for file 'C:\Users\chall\AppData\Local\Temp\Rtmpi6Xgiq\remotesd683ba37dba\DillonHammill-CytoExploreR-7b567c9/DESCRIPTION' (551ms)
-  preparing 'CytoExploreR': (2.4s)
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts (958ms)
-  checking for empty or unneeded directories
-  building 'CytoExploreR_1.0.3.tar.gz'
   
* installing *source* package 'CytoExploreR' ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Error: package or namespace load failed for 'flowWorkspace':
 (converted from warning) multiple methods tables found for 'plot'
Error: package 'flowWorkspace' could not be loaded
Execution halted
ERROR: lazy loading failed for package 'CytoExploreR'
* removing 'C:/Program Files/R/R-devel/library/CytoExploreR'
Error: Failed to install 'CytoExploreR' from GitHub:
  (converted from warning) installation of package ‘C:/Users/chall/AppData/Local/Temp/Rtmpi6Xgiq/filed6870296109/CytoExploreR_1.0.3.tar.gz’ had non-zero exit status
```
My currently installed packages are:
cytoExploreRdata 1.0.1
flowCore 1.53.13
flowWorkspace 3.35.12
openCyto 1.25.2

**Comment by hally166** [comment]
After stepping back and reading the error I can recreate the error message mentioned when loading flowWorkspace. 
```
> library(flowWorkspace)
As part of improvements to flowWorkspace, some behavior of
GatingSet objects has changed. For details, please read the section
titled "The cytoframe and cytoset classes" in the package vignette:

  vignette("flowWorkspace-Introduction", "flowWorkspace")
Warning message:
multiple methods tables found for ‘plot’ 
```

**Comment by DillonHammill** [comment]
@hally166 you are almost there! This is to do with the `remotes` package, it now tgrows an error when installing packages that generate warnings. You can turn thus off as follows:
```{r}
Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true")
```
And then try installing CytoExploreR again and you should be good to go!

FYI I gave recorded an installation video with these instructions, I will post it tomorrow.

**Comment by hally166** [comment]
Fantastic.  It's now installed.
Thank you for all the help. 
Now time to analyse some data.

**Comment by hally166** [comment]
Fantastic. It's now installed.
Thank you for all the help.
Now time to analyse some data.

**Comment by hally166** [comment]
Follow #12 and run `Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true")` as mentioned above.

**Comment by DillonHammill** [comment]
Excellent! I would start by following the Getting Started vignette fir a broad overview:
https://dillonhammill.github.io/CytoExploreR/articles/CytoExploreR.html

Let me know if you need any help :)
