### ISSUE TITLE
getting error while running cyto_gate_draw()

### ISSUE THREAD

**Issue by rwbaer** [DillonHammill/CytoExploreR#91]
**Briefly describe what you hope to achieve:**
I'm trying to run the "getting started code" to verify that I have a working install on a brand new computer.
I used the development version from bioconductor as a basis for installing the rglab packages
The rlang package has been a little finicky during install but I don't know if that could be related.

**Outline the steps taken to attempt to reach this goal (paste code below):**
cyto_gate_draw() fails and produces the traceback below

In my hands, I don't even get a graph displayed to draw points on.  
```{r}
## section 4.1
# Setup compensation controls
gs <- cyto_setup("Compensation-Samples",
                 gatingTemplate = "Compensation-gatingTemplate.csv")

# Transform fluorescent channels - default logicle transformations
gs <- cyto_transform(gs)

# Gate Cells

cyto_gate_draw(gs,
               parent = "root",
               alias = "Cells",
               channels = c("FSC-A", "SSC-A"))

# Gate Single Cells
cyto_gate_draw(gs,
               parent = "Cells",
               alias = "Single Cells",
               channels = c("FSC-A", "FSC-H"))
```

```{r}
Loading FCS files into a GatingSet...
Assigning markers to channels...
Experiment-Markers.csv found in working directory.
Updating experiment details...
Experiment-Details.csv found in working directory.
Setting Compensation-gatingTemplate.csv as the active gatingTemplate...
Done!
Error in FUN(X[[i]], ...) : A minimum of 3 points is required to construct a polygon gate.
12.
stop("A minimum of 3 points is required to construct a polygon gate.")
11.
FUN(X[[i]], ...)
10.
lapply(alias, function(alias) { message(paste("Select at least 3 points to construct a polygon gate around the", alias, "population. \n")) options(show.error.messages = FALSE) ...
9.
.cyto_gate_polygon_draw(fr_list[[1]], channels = channels, alias = alias, plot = FALSE, label = label, gate_point_shape = gate_point_shape, gate_point_size = gate_point_size, gate_point_col = gate_point_col, gate_point_col_alpha = gate_point_col_alpha, gate_line_type = gate_line_type, ...
8.
(function (type, alias) { if (type == "polygon") { .cyto_gate_polygon_draw(fr_list[[1]], channels = channels, ...
7.
mapply(function(type, alias) { if (type == "polygon") { .cyto_gate_polygon_draw(fr_list[[1]], channels = channels, alias = alias, plot = FALSE, label = label, gate_point_shape = gate_point_shape, ...
6.
cyto_gate_draw.flowFrame(fr_list[[z]][[1]], alias = unlist(alias), channels = channels, type = type, negate = negate, display = 1, axis = axis, label = label, plot = FALSE, gate_point_shape = gate_point_shape, gate_point_size = gate_point_size, gate_point_col = gate_point_col, ...
5.
cyto_gate_draw(fr_list[[z]][[1]], alias = unlist(alias), channels = channels, type = type, negate = negate, display = 1, axis = axis, label = label, plot = FALSE, gate_point_shape = gate_point_shape, gate_point_size = gate_point_size, gate_point_col = gate_point_col, gate_point_col_alpha = gate_point_col_alpha, ...
4.
FUN(X[[i]], ...)
3.
lapply(seq_along(fr_list), function(z) { if (plot == TRUE) { if (parent == "root") { prnt <- "All Events" ...
2.
cyto_gate_draw.GatingSet(gs, parent = "root", alias = "Cells", channels = c("FSC-A", "SSC-A"))
1.
cyto_gate_draw(gs, parent = "root", alias = "Cells", channels = c("FSC-A", "SSC-A"))

```

**Include any associated screenshots or images here:**

**Comment by rwbaer** [comment]
Never mind (sort of).  I have been teaching a class where I have been using notebooks, and accidently was trying to run the code in sections from an .Rmd file.   Apparently, that doesn't work, even with the default popup = TRUE.  Making it into an R script seems to mean I'm back in business.

Not closing in case this is not expected behavior for popup = TRUE

**Comment by DillonHammill** [comment]
@rwbaer, `rmarkdown` has been designed to render documents non-interactively so this means that you won't be able to gate whilst rendering the document. You can however, run the individual gating chunks separately, draw the gates and then save the image to include in your rendered document. This will generate a gatingTemplate with all of your gates. Once you have done this, you can prevent the gating chunks from being run when the document is rendered by setting `eval = FALSE` in the chunk options and include a line to apply the gatingTemplate (i.e. `cyto_gatingTemplate_apply(gs, "gatingTemplate.csv")`.

**Comment by rwbaer** [comment]
@DillonHammill .  As always thanks for the valuable feedback and the great package!
