### ISSUE TITLE
cyto_spillover_compute  - dropdown list

### ISSUE THREAD

**Issue by rwbaer** [DillonHammill/CytoExploreR#94]
**Briefly describe what you hope to achieve:**
I'm running what basically amounts to the Getting started script for compensation correction but with only 3 markers.  The FCS files contain height, area, width for 4 channels, but I have deleted height and width for all but FSC-HEIGHT when running cyto_setup().  The first thing I note is that cyto_transform() continues to graph all channels.  Perhaps this is expected.  I then draw my gates and everything seems normal.  

Finally, I run cyto_spillover_compute(), and the channel selector only gives me FL1-HEIGHT as a choice in the dropdown.  As nearly as I can tell this should not be in the dropdown at all, but FL1-AREA, FL3-AREA, and FL4-AREA should.  Any hint as to what is going wrong.  Don't know if there is any overlap with issue 58. The files in question are available here: https://drive.google.com/file/d/1sZFCgqNTHzkkyA_jE4znSXVqcM1zlEzM/view?usp=sharing.

EDIT Addendum:  If I forget the dropdown and jus manually label the 3 standards FL1-AREA, FL3-AREA, and FL4-AREA, I only get a single graph to draw the positive rectangle around and it does not progress after I draw that rectangle.

```{r}
library(CytoExploreR)


# Spill correction
# Setup compensation controls
gs <- cyto_setup("Spill",
                 gatingTemplate = "spill.csv")

# Transform fluorescent channels - default logicle transformations
gs <- cyto_transform(gs)

# Gate Cells
cyto_gate_draw(gs,
               parent = "root",
               alias = "Cells",
               channels = c("FSC-AREA", "SSC-AREA"))

# Gate Single Cells
cyto_gate_draw(gs,
               parent = "Cells",
               alias = "Single Cells",
               channels = c("FSC-AREA", "FSC-HEIGHT"))

# Compute spillover matrix
spill <- cyto_spillover_compute(gs,
                                parent = "Single Cells",
                                spillover = "Spillover-Matrix.csv")

```
![ExperMarkEditor](https://user-images.githubusercontent.com/3155051/97784702-66cd1180-1b6e-11eb-8ad9-475348de31ae.png)
![ChannelSelectorChoices](https://user-images.githubusercontent.com/3155051/97784703-66cd1180-1b6e-11eb-80ad-ad558a5bb680.png)

**Include any associated screenshots or images here:**

**Comment by rwbaer** [comment]
I thought I'd ping this post with the hope you are just busy and not in a COVID way. I know you are working on a refactor that may make this easier to address on the other side, but I thought I'd seek help again and make sure you can access the example I supplied.

**Comment by DillonHammill** [comment]
What is the output of `cyto_channels(gs)` and `cyto_markers(gs)` after running `cyto_setup()`?

**Comment by rwbaer** [comment]
They return the following:
```
> cyto_channels(gs)
 [1] "TIME_MSW"   "TIME_LSW"   "FSC-HEIGHT" "FSC-AREA"   "FSC-WIDTH" 
 [6] "SSC-HEIGHT" "SSC-AREA"   "SSC-WIDTH"  "FL1-HEIGHT" "FL1-AREA"  
[11] "FL1-WIDTH"  "FL2-HEIGHT" "FL2-AREA"   "FL2-WIDTH"  "FL3-HEIGHT"
[16] "FL3-AREA"   "FL3-WIDTH"  "FL4-HEIGHT" "FL4-AREA"   "FL4-WIDTH" 
[21] "SORT"      
> cyto_markers(gs)
    TIME_LSW   FSC-HEIGHT     FSC-AREA     SSC-AREA     FL1-AREA     FL3-AREA 
      "TIME" "FSC-HEIGHT"   "FSC-AREA"   "SSC-AREA"   "FL1-AREA"   "FL3-AREA" 
    FL4-AREA 
  "FL4-AREA" 
```

**Comment by DillonHammill** [comment]
Just double checking, did you set `restrict = TRUE` in `cyto_setup()`?

**Comment by DillonHammill** [comment]
Not entirely sure what is going on, the channel selector simply takes on the output of `cyto_fluor_channels()` which seems correct above. Are you sure that the options are not just truncated due to limited space in the table. Can you try typing the name of of a different channel in the box and see if it highlihhts an option in the dropdown menu?

**Comment by rwbaer** [comment]
So the first problem was **my** failure to set `restrict = TRUE` in `cyto_setup()`.  That helped a lot.   It also changes the one available item in the dropdown from FL1-HEIGHT to FL1-AREA.  However, it does NOT make FL3-AREA or FL4-AREA available in the dropdown.
```
> cyto_fluor_channels(gs)
[1] "FL1-AREA" "FL3-AREA" "FL4-AREA"
```

But,  if I type FL3-AREA next  its standard  and FL4-AREA next to its standard,   I get the expected series of 3 plots to let me mark rectangular gates for neg and pos peaks.  When done, I have a file spillove_Matrix.csv that seems to be what I need so this help lets me move forward.

**Comment by DillonHammill** [comment]
Yeah, the dropdown options are there, but there is not sufgicient space to display them. The solution is to start typing what you want and it will display the best matching option. You can either select it from the dropdown then or type the complete name.

**Comment by rwbaer** [comment]
Thanks for the help and the final tip.
