### ISSUE TITLE
cyto_setup() Recursive issue

### ISSUE THREAD

**Issue by rwbaer** [DillonHammill/CytoExploreR#97]
**Briefly describe what you hope to achieve:**
I am going through the `cyto_setup()` process but when I collected my spill standards I collected a couple of samples that I don't want to use in the final process.  I therefore created an "unused" subfolder and dumped the extra calibration samples in there.  When I run cyto_setup(), it finds the unused folder and apparently doesn't ignore it.  

I looked for something like pattern = ".fcs" or recursive = FALSE to help eliminate its chocking but I could not find such a thing.  Is there a way to get it to ignore this "unused" subfolder? 

Undesirable workaround:  If I remove the "unused" folder from the "spill" folder everything proceeds as expected.

**Outline the steps taken to attempt to reach this goal (paste code below):**
- Include all data preparation steps where appropriate.
```{r}
> gs <- cyto_setup(path = "./2020-02-29 Phagocytosis(2h)_04/Spill",
+                  gatingTemplate = "spill.csv", 
+                  restrict = TRUE)
Loading FCS files into a GatingSet...
Error in fcs_to_cytoset(sapply(files, normalizePath), list(which.lines = which.lines,  : 
  can't open the file: D:\RStudioProjects\Phagocytosis\2020-02-29 Phagocytosis(2h)_04\Spill\Unused
Please check if the path is normalized to be recognized by c++!
> 
```

**Include any associated screenshots or images here:**

**Comment by DillonHammill** [comment]
See `exclude` and `select` arguments for `cyto_load()` which is called by `cyto_setup()`

```{r}
gs <- cyto_setup(path = "./2020-02-29 Phagocytosis(2h)_04/Spill",
                 gatingTemplate = "spill.csv", 
                 restrict = TRUE,
                 exclude = "Unused")
```

Alternatively,
```{r}
gs <- cyto_setup(path = "./2020-02-29 Phagocytosis(2h)_04/Spill",
                 gatingTemplate = "spill.csv", 
                 restrict = TRUE,
                 select = ".fcs")
```

**Comment by rwbaer** [comment]
Thanks so much.  BTW, I did look at  ?cyto_setup before posting, including "additional arguments passed to load_cytoset_from_fcs." and didn't find them.  I feel badly to keep bothering you, but be assured that I am grateful for your package and your awesome help.
